### ISSUE TITLE
un-published project being displayed

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#107]
Logged in as admin. Created project (Housing Data: BCIC Innovation Exchange™ Public Service Challenge for BC Stats) but did not publish. 

![image](https://cloud.githubusercontent.com/assets/11237533/22810754/76e3b6b4-eeef-11e6-9924-834a3b244ef9.png)

![image](https://cloud.githubusercontent.com/assets/11237533/22810779/8d6575d0-eeef-11e6-994d-c642433426e5.png)

**Comment by mark-a-wilson** [comment]
@paulroberts68 Is the point that the user should not be able to publish an opportunity if the project page is unpublished? (Makes sense)

**Comment by ccoldwell** [comment]
found this in both the case of opps and projects

**Comment by mark-a-wilson** [comment]
Tested. 
Logged in as admin:
- unpublished the program page
- navigated to project list page. The projects under that program now have also been unpublished.
- navigated back to program page. published. navigated back to project list page, and the project is now also re-published.
(nice work!)

As a user, not logged in:
- unpublished program and child projects are not appearing (correctly)
