### ISSUE TITLE
As an authorized government user I can't create projects for a program

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#109]
As a verified government user who has been confirmed as a member of a program I can't create new projects for that program

![image](https://cloud.githubusercontent.com/assets/11237533/22811070/82b3886e-eef1-11e6-9b7f-238128e9ae95.png)

**Comment by mark-a-wilson** [comment]
Removing bug label and putting this in backlog as I believe this is the way we've designed it to work for now - i.e. only the creator of a program can create projects and opportunities under that project. We can discuss if permissions need to change - i.e. if any member of a program should be able to create projects or opportunities under that program...

**Comment by mark-a-wilson** [comment]
closing for now.
