### ISSUE TITLE
Should there not be a header for the project card>

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#110]
It's slightly confusing not to have a header for the project card. It would be useful to see membership, skills and status. @mark-a-wilson is there a design reason?

![image](https://cloud.githubusercontent.com/assets/11237533/22811219/5f579be8-eef2-11e6-995e-e8c526769166.png)

**Comment by mark-a-wilson** [comment]
These headers only appear to the creator of the project, but yes, they should appear. This was noted under https://github.com/BCDevExchange/devex/issues/52. Closing as this is duplicate.

**Comment by mark-a-wilson** [comment]
This was in the TEST column - just reconfirming that they are appearing now in test.
