### ISSUE TITLE
"Admin Local" user showing as a "Program Member" on all Program pages 

### ISSUE THREAD

**Issue by sheaphillips** [BCDevExchange/devex#111]
"Admin Local" is showing as member on all program pages.

Since this is an system/internal account, and not really a user/member it seems like we should suppress showing this account on program pages and elsewhere.
<img width="667" alt="screenshot 2017-02-10 09 03 21" src="https://cloud.githubusercontent.com/assets/698658/22836133/0964f5cc-ef70-11e6-9ce0-7c635f8c8c37.png">

**Comment by mark-a-wilson** [comment]
chris hid - beauty!
