### ISSUE TITLE
Use a default/placeholder image (instead of showing broken image icon) if users haven't uploaded a profile photo.

### ISSUE THREAD

**Issue by sheaphillips** [BCDevExchange/devex#112]
Currently, a "broken image" icon shows when a user hasn't uploaded a profile pic.  This gives the impression that something is broken in the app, and it may not be obvious to new users that they need to do something to "fix" it.

Suggestion is to have a placeholder/default image instead of the broken image icon, as would be done on most sites.

**Comment by mark-a-wilson** [comment]
Tested this in PROD with a new gov user who Sign Up to GitHub on their Sign Up to the DevX App process..... her GitHub placeholder avatar was carried over.

So, since the only way someone can Sign Up on our App is by first signing up to GitHub, I think we're good now!
