### ISSUE TITLE
Forbidden error msg when navigating back to program page from GitHub

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#115]
Got this error when logged in as Admin and when not logged in:
- In Environmental Reporting BC program page, clicked on "View an index of our GitHub..." link at bottom of description
- on the GitHub page, clicked the back button to go back to Program page, and got "Forbidden" error.

**Comment by ccoldwell** [comment]
cannot reproduce from platform-test
tried every link in the description, including view our website

**Comment by mark-a-wilson** [comment]
Tested.
Error message not happening when signed in as **admin**. 

But **is** still happening when not signed in:
- From Environmental Reporting BC program detail page, clicked on "View an index of all our GitHub repositories" link at bottom of description. 
- From GitHub page, clicked back button: "Forbidden" error.
- (in addition) navigated back to the Programs list page, clicked on Environmental Reporting BC and also got the "Forbidden" error.

**Comment by ccoldwell** [comment]
Still cannot reproduce using any browser with any combination of links.
This oes not sound like anything to do with the code of our site, it likely has to do with your browser, or some setting in it.  I would have to see you having the actual error.  There is nothing in our code that would cause this
