### ISSUE TITLE
Unpublished opportunities being displayed in a project

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#116]
Create 5 opportunities but did not publish.

![image](https://cloud.githubusercontent.com/assets/11237533/22989637/813b8468-f36b-11e6-978d-489a84e6cf60.png)

**Comment by ccoldwell** [comment]
Tested this, but could not reproduce - if you create the opportunity it will show for you, but not others. Try logging out and look again at the project

**Comment by ccoldwell** [comment]
investigated further and located error - fixed

**Comment by mark-a-wilson** [comment]
Tested. Working correctly now: 
As admin, unpublished opportunity does appear on the Project page, but it shows with the 'Unpublished' badge. As an user not signed in, the unpublished opportunity does not appear on the Project page.
