### ISSUE TITLE
Opportunity - create/edit form

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#12]
The more I think about it, I'm not sure if we can get away with *not* providing options for formatting (e.g. bold text, hyperlinking text, bulleted and numbered lists, headings) on these parts of the form:

- Full description
- Acceptance criteria
- Evaluation criteria

- [x] Add basic WYSIWYG editor to the fields in the list above.

**Comment by mark-a-wilson** [comment]
- [ ] remove breadcrumb.  (Cancel or Save will take the user back to where they came from - the Opportunities list page, or a Project detail page.)

**Comment by mark-a-wilson** [comment]
- [ ] Need to add a basic *well* (see [Theme](http://design-devex-platform-dev.pathfinder.gov.bc.ca/theme.html)) to the top of the form where I can add links to more content about Code With Us.

**Comment by mark-a-wilson** [comment]
Currently, on 'Save', the user is sent back to the Opportunities list page. 
- [ ] Change so that on 'Save', the user is taken to the Opportunity Detail page (with options to 'Edit', or 'Publish' if all fields are complete. (On 'Cancel', user should be taken back to the page from which they initiated the 'Post an Opportunity' button.)

**Comment by mark-a-wilson** [comment]
- [ ] On clicking 'Cancel', user should be taken back to the page from which they initiated the 'Post an Opportunity' button.

**Comment by mark-a-wilson** [comment]
- [ ] Remove GitHub field

**Comment by mark-a-wilson** [comment]
- [ ] Move **Required skills** field beneath **Description**

**Comment by ccoldwell** [comment]
description / skills / acceptance / proposal / dates

**Comment by mark-a-wilson** [comment]
- [ ] '?' beside Project field -- change to a blue dropdown instead of hover-over (like the rest)

**Comment by mark-a-wilson** [comment]
Done
