### ISSUE TITLE
Remove Sprint With Us Design Sprint from website landing page

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/devex#126]
On here: https://bcdevexchange.org

Move BCTech Summit first.

Remove this content: 

Co-Design Meetup: Sprint With Us!

Come help us shape a model for qualifying and quickly hiring developers onto government sprint teams. Food and beverages provided!

Wed, February 22, 2017 / 7:00 PM
1012 Douglas Street, Victoria

RSVP

Replace it with this:
 
BCDevExchange Meetup

Come network with leaders in the tech and public sectors and share stories of innovation. Food and beverages provided!

Wed, March 29, 2017 / 6:00 PM
1012 Douglas Street, Victoria

RSVP

**Comment by mark-a-wilson** [comment]
Thanks Loren - sorry, I had done this days ago, but forgot to get it pushed to PROD.
