### ISSUE TITLE
funky stuff going on with create projects in PROD

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#129]
Experiencing these things as admin local:

- New Project form has WYSIWYGs gone and help text automatically exposed
- Save button doesn't work
- Cancel button causes 'Forbidden' error msg
- ' + CREATE NEW PROJECT' button missing from projects section on program detail pages

**Comment by mark-a-wilson** [comment]
Looked at this just now in TEST:

- New Project form is back to being the right way
- Save button works
- Cancel button works
- ' + Create NEW PROJECT' button still missing from projects section on program detail pages

**Comment by ccoldwell** [comment]
Whenever you see such errors, please open the console and cut and paste all the output into the ticket.  Typically if the wysiwig fields don't show it means something unrelated is happening.

**Comment by ccoldwell** [comment]
new project button is present on program detail page
