### ISSUE TITLE
Paid opportunity: Deliver a notification system for the BCDevExchange Application

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#136]
We are offering a paid opportunity for someone to deliver code that will automate notifications from our app. We want to use the skeleton of this notification system for other future rules that we haven't determined yet.

### Please [visit the opportunity on bcdevexchange.org](https://bcdevexchange.org/opportunities/opp-email-notification-system-for-bcdevexchange-application) for full details.

I am the UX designer for the app, and @ccoldwell is our lead developer. If you have any questions or comments, we'd be delighted to respond to your comments below. Thanks for your interest!

**Comment by mark-a-wilson** [comment]
Hello @VldmrPvlvc, @khirwaa, @mitozv, @VistaBayConsulting, @rafael-trevisan, @exe2000, @johannamcburnie, @monicag, @dskvr, @spallister, @gowheth, @jonabrow, @kimberleyhansen, @cuell, @c3ilabuser - just wanted to notify you to this opportunity.

If you'd prefer to receive notifications by email, please sign in on [bcdevexchange.org](https://bcdevexchange.org) and add an email address to your profile. 

Or, of course let me know if you don't want to be notified or tagged.

Thanks!

**Comment by jaypersanchez** [comment]
Hello and thank you for the email notification for this project.  I'd like to fully understand how things are done currently so I do have a few questions with how you currently gather these data. 

1. How is a government or public sector user information collected and stored?

2. How do you verify the identity of new government/public sector users?  Is it safe to assume that these information is in some sort of repository like database or even Excel file?

3. How big is the data that has all the email address that is used for email distribution?

4.  How are you notified when a new paid opportunity is published? 

5. Are you open to the idea of an external hosted app that will run this notification engine?

Thanks in advance for the clarification.

**Comment by mark-a-wilson** [comment]
**Notice**: I have just made some updates / changes to the [Acceptance Criteria](https://bcdevexchange.org/opportunities/opp-email-notification-system-for-bcdevexchange-application) based on internal feedback on how to be more clear about what we'd like delivered.

**Comment by mark-a-wilson** [comment]
Hi @jaypersanchez , thanks for your interest. I'm going to try to answer what I can here, and ask @ccoldwell to fill in the holes…

2. Currently, we (as site admin) verify gov/public sector users by taking a look at their email address and cross-referencing it with our internal gov contacts. (To date, it's all people that we know, and we are only granting gov permissions to people we know are British Columbia public sector employees).

3. Not that big

4. Not sure if this is what you were asking, but currently, we have been keeping a big excel sheet with our email contacts, and manually emailing people every time. The acceptance criteria (hopefully) describes how we’d like this to be automated. 

5. No. We need this to be an on-premise/hosted service. We can’t consider external/SASS solutions.

**Comment by johannamcburnie** [comment]
Hi there,

My company would love to submit a proposal for this opportunity. However, we are facing a barrier when it comes to offering links to our relevant GitHub projects. All of the projects we work on are in private repositories. Are links necessary to be considered for this opportunity?

Thanks

**Comment by mark-a-wilson** [comment]
Hi @johannamcburnie 

Access to your GitHub projects is not a requirement, just an example of one way to demonstrate your ability in your proposal. Any other work examples we can see (especially code that our dev can check out) are relevant and welcome. 

Also (and not sure if this is what you meant, but just to be clear), our _Code With Us_ model is designed for assigning the opportunity to an **individual** who is committing to do the work, based on that individual’s experience and demonstrated work. (In other words, we don’t want a proposal from a company based on collective work, then have the company decide later who they’ll assign to us.)

Hope that makes it clear?

**Comment by ryanwinchester** [comment]
Does this need to be written in the languages showing up in the labels?

Also, why not just use mailchimp? ;)

**Comment by ccoldwell** [comment]
@ryanwinchester, to answer your question regarding the language(s):

The short answer is "not necessarily".  We would be happy with the system inside the current code base, or outside of it.  The only real requirement is that it can run in our Docker / OpenShift environment, which makes some languages/frameworks/architectures a lot easier than others.  It also has to be able to be integrated with the system for automatic notifications based on events, so some sort of RESTful API would be required.

**Comment by ryanwinchester** [comment]
My weapon of choice these days is Elixir.

For a somewhat relatable comparison, Pinterest rewrote their notification system in Elixir:

> Pinterest’s notification system now uses Elixir to deliver 14,000 notifications per second. The notification system runs across 15 servers, whereas the old system, written in Java, ran on 30. The new code is about one-tenth of the size of the old code.
-- from  [Why Pinterest just open-sourced new tools for the Elixir programming language](http://venturebeat.com/2015/12/18/pinterest-elixir/)

**Comment by mark-a-wilson** [comment]
@ryanwinchester - re: mailchimp - as gov, we run into a lot of restrictions around using external services due to data being stored outside Canada.

**Comment by ccoldwell** [comment]
@ryanwinchester - I like Elixer, wanted to find a reason to use it for ages.  I believe it requires an erlang vm though, so just see if that plays well with docker and openshift.

**Comment by melavo** [comment]
I like the Notify BC api, will you be extending this to sms notification as well as email?

**Comment by mark-a-wilson** [comment]
@melavo I (for one) had not thought that far ahead, but a solution that considered that option would be attractive.

**Comment by mark-a-wilson** [comment]
Hello anyone who's watching: Just a friendly reminder that the deadline for proposals is **tomorrow** at **16:00 Pacific**. [See here](https://bcdevexchange.org/opportunities/opp-email-notification-system-for-bcdevexchange-application) for details.

**Comment by ryanwinchester** [comment]
@ccoldwell Looks like there is [openshift stuff for erlang/elixir](https://github.com/wozniakjan/erlcart). Also, I know of some people who use [elixir with docker](https://semaphoreci.com/community/tutorials/dockerizing-elixir-and-phoenix-applications). However, I don't think deploying with docker will take advantage of some the erlang vm's great features like hot code upgrading.

Still, it would be fun to do. However, I'm not familiar enough with openshift or docker to throw my hat in the ring.

**Comment by Mando-Chris** [comment]
Hello @mark-a-wilson 

I just became aware of the new BCDevExchange site, and I am thinking of submitting a proposal for this project.

Some last minute questions

1. Since you can't use an external service to send the notifications, I assume you have an internal mail server and we would use directly?  And if so, what sort of email volumes are we currently looking at?
1. The timeline is very short, criteria to be met within 14 days of the project entry being closed. If progress is being made, will that deadline be flexible at all?

Thanks

**Comment by Mando-Chris** [comment]
And more follow up questions

1. Do you have a desired template designed for the email body?  
1. For editing the email body is a simple Text sufficient, or is Rich Text Editing a requirement?

Thanks

**Comment by mark-a-wilson** [comment]
@Mando-Chris thanks for your inquiries and sorry for the delay.

Re: timeline ... we'd like the assignee to commit incrementally up to March 31, but the requirement is that you'd need to, at minimum, submit the first pull request before or on 31st March. There may be a need for a couple of revisions based on initial feedback so completion and final acceptance of the work could extend into the first couple weeks of April. 

Re: template for email body ... no, I don't. It would be great if you could design something that aligns with the colors and brand of the current site.

Re: editing the email body, I think Rich Text might be a requirement, so if that could be included.

**Comment by ccoldwell** [comment]
@Mando-Chris - re: mail server, yes, we have a relay that you can use, the volumes will be low

**Comment by melavo** [comment]
Is this the right form to attach? https://github.com/BCDevExchange/code-with-us/raw/master/Code%20With%20Us%20Paid%20Terms_Nov_28.pdf.  Where is say which ministry, put Ministry of Technology?   [Insert Ministry contact information, including title, business address and
business telephone number].  The previous form I filled out had it all filled out and a spot to put in my name and contact.

**Comment by mark-a-wilson** [comment]
@melavo yes, that's the one, and sorry it's missing the Ministry contact info.. I will be sure to provide that info to everyone who applies. And don't worry about inserting your info in the document, you can just provide it in the body of your email.

**Comment by mark-a-wilson** [comment]
Thank you to everyone who took the time to comment and to the 6 who sent a proposal. We will evaluate and announce an assignee here on Monday.

**Comment by mark-a-wilson** [comment]
Hello everyone, sorry for the delay. We have evaluated proposals and are assigning this opportunity to Chris Gat.

---

If you would like feedback on your proposal, please [email me](mailto:Mark.Wilson@gov.bc.ca).

---

If you have any questions around the collection of your information for the proposal, you can find the contact information for your inquiry on pg. 5 of [this document](https://github.com/BCDevExchange/devex/raw/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf).

**Comment by mark-a-wilson** [comment]
Closing.
