### ISSUE TITLE
Project - detail page

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#14]
- [x] Remove "*Project:*" from title

Project Members cards:  
- [x] Remove "Member since..." 
I presume in v0.2, we'll make cards active, leading to individual profile pages; but for v0.1, individual user profiles will not be viewable... (?)

**Comment by ccoldwell** [comment]
take out member since and username, make card link to user profile (everywhere)

**Comment by mark-a-wilson** [comment]
- [ ] Need a button for users who are not admin on the project to request membership. Insert '+ REQUEST MEMBERSHIP' button in **Project Members** section (copy style of '+ POST AN OPPORTUNITY' button).

**Comment by mark-a-wilson** [comment]
![project detail](https://cloud.githubusercontent.com/assets/16946297/21949774/c66839e0-d9a9-11e6-9610-811cecb61516.png)

**Comment by mark-a-wilson** [comment]
- [ ] decrease font size of **Short Description** (everywhere)

**Comment by mark-a-wilson** [comment]
- [ ] Tags (??) What direction do we give to users on what to enter here?

**Comment by mark-a-wilson** [comment]
Could we make the link to the GitHub repo look like this?   (fa-github)

![screen shot 2017-01-17 at 10 29 45 am](https://cloud.githubusercontent.com/assets/16946297/22034142/143d2ba0-dca0-11e6-8abc-e648451a438c.png)

**Comment by mark-a-wilson** [comment]
Done
