### ISSUE TITLE
Delete a user profile

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/devex#140]
Currently when you delete your profile you stay signed in on your profile page. You need to refresh your browser window to be signed out.

This is what should happen:

**A signed in user deletes his or her profile**

Given
A user is signed in
And is on his or her Profile page
When the user clicks "Delete my profile"
Then they should be presented with a modal that asks "Are you sure you want to delete your profile?" with options for "Yes" or "No"
 
If the user Clicks NO on the modal
Then they should be taken back to his or her profile page 
 
If the user clicks YES on the modal
Then the user should be presented with a new modal which confirms that his or her profile has been deleted
And his or her profile should be deleted from the database
And when the user dismisses the modal
Then the user should be signed out and taken back to the home page
And it should say "Signup" or "Signin" on the navigation bar

**Comment by lmullane** [comment]
@ccoldwell Could you give us an estimate on the time to fix this issue. @paulroberts68

**Comment by mark-a-wilson** [comment]
This has been completed, just tested in DEV. 👍 

Given a user is signed in
When the user clicks on 'Delete My Profile'
Then a modal appears which asks "Are you sure?"
And when the user clicks 'Yes'
Then a second modal appears which asks "Are you really sure?"
And when the user clicks 'Yes' again
Then the profile is deleted and the user is taken back to the homepage.

![delete-profile](https://user-images.githubusercontent.com/16946297/28179952-72216328-67b8-11e7-85d1-c5d17092de0f.gif)
