### ISSUE TITLE
A saved opportunity cannot be edited

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/devex#141]
@ccoldwell @paulroberts68 

To replicate:

- Create new opportunity
- Save the opportunity
- Click edit
- edit the opportunity including the date
- Click save
- get red modal with error message "Cannot read property 'getDate' of null"

**Comment by ccoldwell** [comment]
this was a strange problem with date formatting caused by angular doing things automatically in both the front and back end. cleared up both

**Comment by lmullane** [comment]
Thanks @ccoldwell Can you close this issue when you have a moment.
