### ISSUE TITLE
Profile edit nav menu is disabled when display is 767px wide or less

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#145]
The nav menu works when display is wider than 767px, but something is causing it to disable when it gets smaller than that breakpoint.

![screen shot 2017-07-10 at 9 10 42 am](https://user-images.githubusercontent.com/16946297/28027964-d867261a-654f-11e7-9ac8-f22b1af99783.png)

**Comment by ccoldwell** [comment]
tested and seems to work fine on chrome and on safari
