### ISSUE TITLE
Email notifications not received on publish new opportunity

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#153]
As admin
I just published a new opportunity under the DataBC program:
https://bcdevexchange.org/opportunities/opp-nifi-atlas-bridge-development-opportunity--1

I checked with a couple of users who were signed up for notifications -- they didn't receive an email.

**Comment by ccoldwell** [comment]
this bug has been found and addressed and will be fixed in production by the end of the day today
