### ISSUE TITLE
Updating issue title in app is not replicated in GitHub

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/devex#160]
GitHub bot does not allow updates of issue title.

**Comment by ccoldwell** [comment]
Will check this tomorrow

**Comment by mark-a-wilson** [comment]
I have tested this just now in both DEV and TEST. 

- GitHub issue is now being generated upon publish
- Link from "Questions?" on opportunity detail page to the issue is being generated and working
- Link from the issue back to the opportunity detail page is being generated and working

🎉   🎉
