### ISSUE TITLE
This opportunity is open to all, but I'm going to assign it to Paul

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#166]
<p>Need you to push our project forward - fast!</p><h2>Acceptance Criteria</h2><p>You must make us make progress</p><h2>Proposal Evaluation Criteria</h2><p>1. Your name begins with "P"</p>
<p>2. Your name ends with "aul"</p>

**Comment by ccoldwell** [comment]
This opportunity has been assigned

**Comment by mark-a-wilson** [comment]
closing -- this was a test

**Comment by ccoldwell** [comment]
This opportunity has been un-assigned
