### ISSUE TITLE
Opportunity Detail Content on the Issue in GitHub (formatting)

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#171]
Value: $2,000.00Closes: 23:00 PST, Monday, October 16, 2017Location: Victoria In-person work NOT required<h2>Opportunity Description</h2><p>This is the full description.....</p><h2>Acceptance Criteria</h2><p>This is the acceptance criteria</p>
<p>1.&nbsp;</p>
<p>2.&nbsp;</p>
<p>3. four</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-opportunity-detail-content-on-the-issue-in-github--formatting-">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on 23:00 PST, Monday, October 16, 2017</b>.</p><p>We plan to assign this opportunity by <b>Monday, October 16, 2017</b> with work to start on <b>Monday, October 16, 2017</b>.</p><p>If your proposal is accepted and you are assigned to the opportunity, you will be notified by email and asked to confirm your agreement to the <a href="https://github.com/BCDevExchange/devex/raw/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf"><i>Code With Us</i> terms and contract.</a></p><h2>Proposal Evaluation Criteria</h2><p>asdfasdf</p>
<p>asdfas</p>
<p>asdfasd</p>
<p>f</p>

**Comment by mark-a-wilson** [comment]
This was just as a test for formatting.
