### ISSUE TITLE
Deliver a new web theme for the BCDevExchange app

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#176]
Value: $6,500.00Closes: 0:00 PST, Thursday, November 23, 2017Location: Victoria In-person work NOT required<h2>Opportunity Description</h2><p>We would like to apply a fresh look to BCDevExchange.org.</p>
<p>We would like you to deliver to use Bootstrap 4 template, with styling in SCSS.</p><h2>Acceptance Criteria</h2><ol>
<li>Meet with our 4-person team (in-person or remotely) to understand our goals for the application.</li>
<li>Create&nbsp;a custom Bootstrap 4 theme using SCSS for the BCDevExchange app.</li>
<li>Deliver a first iteration of the theme as a pull request (or series of pull requests) to our <a title="public code repository" href="https://github.com/BCDevExchange/devex" target="_blank" rel="noopener noreferrer">public code repository</a>.</li>
<li>Demonstrate that the theme can be "swapped in" - that it integrates fully with&nbsp;the&nbsp;existing soure code. (Our team will verify this by deploying your pull request in our DEVELOPMENT environment and&nbsp;conducting a thorough site test.)</li>
<li>Work with our technical contact to deliver successive commits to address any gaps identified, to the point where your new theme can be swapped in and pushed to PRODUCTION.</li>
</ol>
<p>&nbsp;</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-deliver-a-new-web-theme-for-the-bcdevexchange-app">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on 0:00 PST, Thursday, November 23, 2017</b>.</p><p>We plan to assign this opportunity by <b>Saturday, December 2, 2017</b> with work to start on <b>Saturday, December 2, 2017</b>.</p><p>If your proposal is accepted and you are assigned to the opportunity, you will be notified by email and asked to confirm your agreement to the <a href="https://github.com/BCDevExchange/devex/raw/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf"><i>Code With Us</i> terms and contract.</a></p><h2>Proposal Evaluation Criteria</h2><p>1. The quality of past examples of your work that uses Bootstrap theme. (30 points)</p>
<p>2. Your depth of experience working with clients to design branding. (20 points)</p>
<p>3. Your availability to start working with us right away and finish work before Dec 20, 2017. (10 points)</p>

**Comment by ccoldwell** [comment]
This opportunity has been assigned

**Comment by mark-a-wilson** [comment]
This was a "fake" opportunity for a demonstration today.
