### ISSUE TITLE
Create a company blooper 1

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#190]
As a signed in user
When I navigate to the company tab
And I enter information into the fields and save
And I upload a company image 
Then press save
I get a 'forbidden' error then
When I navigate back
I loose all the app information except the header and footer.
![image](https://user-images.githubusercontent.com/11237533/34503427-115b9854-efcd-11e7-82d9-6aa32a1b659c.png)

And when I sign out then in I can see my company
![image](https://user-images.githubusercontent.com/11237533/34503462-510bf7a0-efcd-11e7-80ce-081ee36ac9f9.png)

Then when I click on the company I see
![image](https://user-images.githubusercontent.com/11237533/34503500-7e514706-efcd-11e7-8077-eccb81bc3b7d.png)

**Comment by ccoldwell** [comment]
could not re-create this using the following steps:
1. log in using git
2. browse to company listing
3. click add new company
4. fill out fields
5. hit save
6. fill out remaining fields (address etc)
7. click edit profile image (opens image upload modal)
8. select image
9. click upload (returns to main company edit screen)
10. click save (says company saved)

**Comment by paulroberts68** [comment]
@ccoldwell OK, I'l try and re-create and let you know the result.

**Comment by mark-a-wilson** [comment]
I just recreated this - to the same thing as Paul: 
Uploaded image (OK)
Saved profile (OK)
But then while I was in the company profile section, when I clicked on the Companies in the main nav, I got the same blank screen with the header and footer (no companies in the list). 
Then I did a refresh of the page and that got the companies list back.

**Comment by mark-a-wilson** [comment]
Closing this issue as it is probably obsolete now.
