### ISSUE TITLE
Responding to an opportunity

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#193]
When I have created and published a proposal
Then withdrawn the proposal 
The signed out
When I sign in again
And I navigate to the same opportunity
And I click on submit a proposal I see
![image](https://user-images.githubusercontent.com/11237533/34532290-74d2c4b4-f06a-11e7-92e1-a3526f951e8a.png)

**Comment by ccoldwell** [comment]
I *believe* this has been fixed, sort of by accident while working on the sprint with us feature set. I also used to get this periodically, but have not since

**Comment by mark-a-wilson** [comment]
I followed the same process @paulroberts68, and could not recreate the issue you experienced.

If you **withdraw** a proposal, your proposal is still saved in **draft** - so you shouldn't see the submit a proposal button, you see this banner at the top:

![image](https://user-images.githubusercontent.com/16946297/35363808-ca6b4cb8-0120-11e8-9320-63e4e6edaf20.png)
