### ISSUE TITLE
Text on the CWU terms acknowledgement box

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#200]
The text should read:
[I acknowledge that I have read and fully understand and agree to the terms and conditions.]

![image](https://user-images.githubusercontent.com/11237533/35313695-91f01652-0076-11e8-8221-e22b9f7d76c8.png)

**Comment by ccoldwell** [comment]
changed

**Comment by mark-a-wilson** [comment]
Just checked this in TEST and "**acknowledge**" is still mispelled

**Comment by mark-a-wilson** [comment]
checked the code base and there is no trace of "ackowledge" anymore
