### ISSUE TITLE
Opportunity creation - error message displayed immediately

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#201]
When I select POST AN OPPORTUNITY
The screen immediately displays an error message
![image](https://user-images.githubusercontent.com/11237533/35315518-9d7f5b9e-0081-11e8-98df-10265b9c0847.png)

**Comment by ccoldwell** [comment]
removed this for now.  we need to show this when someone intends to publish (it will be there on the view screen always) but it is not appropriate on the edit screen until they are ready to publish, but how do we know their intent?

**Comment by scchapma** [comment]
Reviewed this in Dev branch today (July 24th).  Certain fields must be filled in before an opportunity can be published.  When an admin saves changes to a draft opportunity, the admin is alerted to any required fields that have not been filled in.   Closing this issue.
