### ISSUE TITLE
UI issues upon creating an opportunity in the TEST environment

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#203]
When I create an opportunity in the TEST environment and fill in all the fields correctly
And I select SAVE
Then I see the opportunity in the draft state
And I also see UI errors at the bottom of the page, misaligned text and an additional EDIT button
![image](https://user-images.githubusercontent.com/11237533/35317407-857c4426-008b-11e8-8f65-5fb33abb4330.png)

**Comment by ccoldwell** [comment]
removed the extra message at the bottom with the old formatting
