### ISSUE TITLE
No publish button on an opportunity in the TEST environment

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#204]
When I complete all the fields in an opportunity 
And I select the SAVE button 
Then I am taken to the opportunity summary page
And I am supposed to see the PUBLISH button but it is missing
![image](https://user-images.githubusercontent.com/11237533/35318018-5f301fa6-008e-11e8-89b9-1cbdb5f905d7.png)

**Comment by ccoldwell** [comment]
You can not publish until all fields have been filled out, so no publish button

**Comment by mark-a-wilson** [comment]
I just re-tested this in TEST and:

1. Saved a draft opportunity with some fields incomplete (result: got the "You can't publish..." warning) - ✅ 
2. Went back in and completed all the fields and re-saved (result: warning message was no longer present, and the publish button was available) ✅ 

🥇
