### ISSUE TITLE
as asd ASD ASD

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#205]
Value: $6,000.00Closes: 0:00 PST, Sunday, November 24, 2019Location: Victoria Some in-person work required<h2>Opportunity Description</h2><p>ASD&nbsp;</p><h2>Acceptance Criteria</h2><p>lkjasdlkjalskdjlkjalsdkjlkjasd lkjasdl kjlaksjd lkj lkajs dlkj laksjd&nbsp;</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-as-asd-asd-asd">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on 0:00 PST, Sunday, November 24, 2019</b>.</p><p>We plan to assign this opportunity by <b>Thursday, June 1, 2017</b> with work to start on <b>Friday, June 2, 2017</b>.</p><p>If your proposal is accepted and you are assigned to the opportunity, you will be notified by email and asked to confirm your agreement to the <a href="https://github.com/BCDevExchange/devex/raw/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf"><i>Code With Us</i> terms and contract.</a></p><h2>Proposal Evaluation Criteria</h2><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

**Comment by paulroberts68** [comment]
Test issue
