### ISSUE TITLE
Jan 24 3:15pm Mark

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#208]
Value: $2,500.00Closes: 0:00 PST, Thursday, January 25, 2018Location: Victoria In-person work NOT required<h2>Opportunity Description</h2><p>This is from the Summary ...&nbsp;</p><h2>Acceptance Criteria</h2><p>asdf</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-jan-24-3-15pm-mark">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on 0:00 PST, Thursday, January 25, 2018</b>.</p><p>We plan to assign this opportunity by <b>Thursday, January 25, 2018</b> with work to start on <b>Wednesday, January 24, 2018</b>.</p><p>If your proposal is accepted and you are assigned to the opportunity, you will be notified by email and asked to confirm your agreement to the <a href="https://github.com/BCDevExchange/devex/raw/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf"><i>Code With Us</i> terms and contract.</a></p><h2>Proposal Evaluation Criteria</h2><p>asdf</p>

**Comment by paulroberts68** [comment]
Test issue
