### ISSUE TITLE
Link to new terms

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#209]
The terms link below links to the old terms. Needs to link to the new terms.
![image](https://user-images.githubusercontent.com/11237533/35363310-40538150-011e-11e8-8757-c12bb57f255c.png)

**Comment by ccoldwell** [comment]
fixed this and also made a full on a proper solution for downloading terms (and any file when it comes to that) as listed in the configuration via a key

**Comment by mark-a-wilson** [comment]
confirmed, this is fixed now https://github.com/BCDevExchange/devex/commit/847ecfeeb2456332eb9c87e9a519fbf80a785895
