### ISSUE TITLE
Maintain BDD Tests as code changes are made

### ISSUE THREAD

**Issue by agehlers** [BCDevExchange/devex#212]
DEVEX team needs to  start working on the BDD tests as part of the release cycle, instead of having Roland fix them when they fail.
BDD tests (create new ones as needed, maintain existing ones as code changes) needs to become part of the release process.

**Comment by plasticviking** [comment]
@ccoldwell A big part of test maintainability is standardizing on naming and identification of key elements for UI testability. Effectively, the test tools grab things via CSS selectors (or Xpath, but CSS is preferred). 

Would it be possible that to create and maintain a standard for naming identifiers or classes for input fields and buttons? At the moment, the only way to reference some of the items is by their relationship to other elements or their text content.

For example,
`$x('//a[@class="nav-link" and contains(.,"Details")]')` when creating a CWU opportunity, to navigate to the 'Details' tab could be simplified greatly (and made less fragile) if it had a known ID like `#detail-tab-link`.

In another case, identifying the edit button for an opportunity with a particular title is constructed in a working but fragile way that could be simplified with some cues (for example, a class like `edit-button` and perhaps even a `data-opportunity-name` or similar html5 attribute to simplify location).

`$x('//div[@class = "card"][div[@class="card-body"]/div[@class="card-title" and contains(., "RandomID")]]//div[@class="card-header"]//a[i[@class[contains(.,"glyphicon-edit")]]]')` 
  (where RandomID is a known token that should exist in the title). This is working but quite fragile.

**Comment by scchapma** [comment]
Rob Johnstone created a new functional test suite that we will maintain and extend moving forward.  Closing this issue.
