### ISSUE TITLE
Location dropdown in user profile

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#214]
It's not just people from B.C. who are users 😄 

Please replace the dropdown with a free text input. It should be blank by default and NOT mandatory.

**Comment by scchapma** [comment]
Let's talk about this.  I don't think we necessarily need to get rid of the existing dropdown, as that dropdown is really useful for BC residents.  However, we do need to include the option of an empty textbox that allows someone who lives out of province (or in province, but at a location not included in the dropdown list) to add their address.

**Comment by scchapma** [comment]
Reviewed this issue in Dev branch today (July 24, 2018).  The user profile view now uses a blank textbox for the "City/Town" field.  Closing this issue.
