### ISSUE TITLE
SWU Opportunity Targeting Bullhorn Bandits

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#223]
Value: $0.00Closes: Thursday, March 1, 2018Location: Victoria In-person work required<h2>Opportunity Description</h2><p>This is a test.</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-swu-opportunity-targeting-bullhorn-bandits">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Thursday, March 1, 2018</b>.</p><p>We plan to assign this opportunity by <b>Thursday, March 8, 2018</b> with work to start on <b>Wednesday, February 14, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by scchapma** [comment]
Opportunity published in error.  Closing issue.
