### ISSUE TITLE
Feb 16

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#224]
Value: $2,000.00Closes: Sunday, February 18, 2018Location: Barriere Some in-person work required<h2>Opportunity Description</h2><p>as;dlkfj</p><h2>Acceptance Criteria</h2><p>asdf</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-feb-16">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Sunday, February 18, 2018</b>.</p><p>We plan to assign this opportunity by <b>Monday, February 19, 2018</b> with work to start on <b>Monday, February 19, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>asdf</p>

**Comment by mark-a-wilson** [comment]
Closing - this was a test
