### ISSUE TITLE
Getting the proposals list back

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#225]
Value: $1,500.00Closes: Wednesday, February 21, 2018Location: Barriere Some in-person work required<h2>Opportunity Description</h2><p>asdf</p><h2>Acceptance Criteria</h2><p>asdf</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-getting-the-proposals-list-back">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Wednesday, February 21, 2018</b>.</p><p>We plan to assign this opportunity by <b>Wednesday, February 21, 2018</b> with work to start on <b>Tuesday, February 20, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>asdfasdf</p>

**Comment by mark-a-wilson** [comment]
This was a test
