### ISSUE TITLE
Finding Capabilities

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#226]
Value: $500.00Closes: Thursday, February 22, 2018Location: Victoria In-person work NOT required<h2>Opportunity Description</h2><p>We logged into DEV, and can't find the capabilities!</p><h2>Acceptance Criteria</h2><ol>
<li>Find the capabilities</li>
<li>Let us poke around with them</li>
</ol><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-finding-capabilities">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Thursday, February 22, 2018</b>.</p><p>We plan to assign this opportunity by <b>Friday, February 23, 2018</b> with work to start on <b>Thursday, February 22, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>1. Tell us you can find them (40 points)</p>

**Comment by mark-a-wilson** [comment]
This was a test
