### ISSUE TITLE
Finding more aardvarks - Part 1

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#227]
Value: $500.00Closes: Thursday, February 22, 2018Location: Victoria In-person work required<h2>Opportunity Description</h2><p>We'll get you up to speed on why we're doing this...</p><h2>Acceptance Criteria</h2><p>Was;ldkfjals;kdfj</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-finding-more-aardvarks---part-1">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Thursday, February 22, 2018</b>.</p><p>We plan to assign this opportunity by <b>Friday, February 23, 2018</b> with work to start on <b>Saturday, February 24, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>as;dlkfj;alskdjf;</p>

**Comment by mark-a-wilson** [comment]
this was a test
