### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#229]
Value: $0.00Closes: Thursday, February 22, 2018Location: Victoria Some in-person work required<h2>Opportunity Description</h2><p>Background</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-title7">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Thursday, February 22, 2018</b>.</p><p>We plan to assign this opportunity by <b>Thursday, February 22, 2018</b> with work to start on <b>Wednesday, February 21, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
this was a test
