### ISSUE TITLE
New one

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#231]
Value: $2,000.00Closes: Friday, February 23, 2018Location: Vancouver In-person work NOT required<h2>Opportunity Description</h2><p>test</p><h2>Acceptance Criteria</h2><p>asdf</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-new-one1">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Friday, February 23, 2018</b>.</p><p>We plan to assign this opportunity by <b>Saturday, February 24, 2018</b> with work to start on <b>Saturday, February 24, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>asdfas</p>

**Comment by mark-a-wilson** [comment]
this was a test
