### ISSUE TITLE
Make sure this persists to the list page....

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#234]
Value: $1,000.00Closes: Thursday, February 22, 2018Location: Victoria In-person work NOT required<h2>Opportunity Description</h2><p>as;ldkfj</p><h2>Acceptance Criteria</h2><p>check</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-make-sure-this-persists-to-the-list-page----">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Thursday, February 22, 2018</b>.</p><p>We plan to assign this opportunity by <b>Saturday, February 24, 2018</b> with work to start on <b>Saturday, February 24, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>check</p>

**Comment by ccoldwell** [comment]
This opportunity has been assigned

**Comment by mark-a-wilson** [comment]
It does persist...working beautifully now!
