### ISSUE TITLE
Feb 22 1:44pm - Testing CWU Opportunities work

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#235]
Value: $1,500.00Closes: Thursday, February 22, 2018Location: Victoria Some in-person work required<h2>Opportunity Description</h2><p>asdfasdf</p><h2>Acceptance Criteria</h2><p>Do this</p>
<p>Do that</p>
<p>&nbsp;</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-feb-22-1-44pm---testing-cwu-opportunities-work">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Thursday, February 22, 2018</b>.</p><p>We plan to assign this opportunity by <b>Friday, February 23, 2018</b> with work to start on <b>Thursday, February 22, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>asd;lkjf</p>

**Comment by mark-a-wilson** [comment]
Link from Opp detail page works

**Comment by ccoldwell** [comment]
This opportunity has been assigned

**Comment by mark-a-wilson** [comment]
This was a test
