### ISSUE TITLE
Signing in for opportunity lands you on home page, not opportunity page

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/devex#237]
Current behaviour:

Given a user is not signed in
And they are on an Opportunity page
Then the user will see a message sign-in to submit a proposal
When the user clicks sign in they will go to the sign page
And when they click sign
Then the user is redirected to the homepage

Expected behaviour:
Then the user is redirected back to the opportunity page

**Comment by scchapma** [comment]
Tested in Dev branch today (July 24, 2018).  The application's behaviour is now consistent with the "expected behaviour" set out above.  Closing this issue.
