### ISSUE TITLE
Change placement of 'Not published' label on Opportunity detail page

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#24]
For consistency:

![list](https://cloud.githubusercontent.com/assets/16946297/22121242/1e35a95e-de38-11e6-8e77-2a2be3dd2d23.png)
![detail](https://cloud.githubusercontent.com/assets/16946297/22121246/2134e9bc-de38-11e6-82bc-e28208dd25f7.png)

**Comment by ccoldwell** [comment]
this is actually a little more complicated as the CSS for that floating label does not have the same wrapping elements on both pages.  This is a css thing that maybe can wait until we have a bunch of similar things to take care of by a front-end dev

**Comment by mark-a-wilson** [comment]
i have changed this around
