### ISSUE TITLE
Improvements to BCDevExchange REST API

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#247]
Value: $10,000.00Closes: Thursday, March 8, 2018Location: Victoria Some in-person work required<h2>Opportunity Description</h2><p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">The BC Developers' Exchange application includes an extenstive REST API. This API allows both users and administrators to navigate the application, access information and respond to posted opportunities.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">We would like to conduct a review of the existing API and implement improvements identified during the review. Additionally, we want to add documentation for the API and add an automated test suite.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">To complete this work, we have identified three distinct milestones:</span>&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; text-decoration-line: underline; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Milestone 1: Review of Current BCDevExchange REST API</span><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><br class="kix-line-break" style="box-sizing: border-box;" /></span><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Review the existing state of the REST API and prepare a detailed analysis of recommended improvements. </span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; text-decoration-line: underline; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Milestone 2: Document REST API and Add Test Suite</span><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; text-decoration-line: underline; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;"><br class="kix-line-break" style="box-sizing: border-box;" /></span><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Implement API documentation using Swagger. Implement an automated test suite using Postman and Newman. </span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; text-decoration-line: underline; text-decoration-skip-ink: none; vertical-align: baseline; white-space: pre-wrap;">Milestone 3: Implement Identified Improvements</span><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><br class="kix-line-break" style="box-sizing: border-box;" /></span><span style="font-family: Calibri;"><span style="font-size: 14.6667px; white-space: pre-wrap;">Implement an agreed upon suite of improvements up to a value of $2,500.</span></span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">The fixed-price reward is for a total of $10,000* for fulfilling the Acceptance Criteria below, per this payment schedule:</span></p>
<ul style="box-sizing: border-box; margin-top: 0pt; margin-bottom: 0pt; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;">
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="box-sizing: border-box; font-size: 11pt; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Completion of milestone 1 - $3,500</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="box-sizing: border-box; font-size: 11pt; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Completion of milestone 2 - $4,000</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="box-sizing: border-box; font-size: 11pt; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Completion of milestone 3 - $2,500</span></li>
</ul>
<p>&nbsp;</p>
<p><span style="box-sizing: border-box; font-size: 11pt; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><span style="font-family: Calibri; font-size: 14.6667px;">*The full amount is dependent on an evaluation of outputs at the end of milestone 1 and the end of milestone 2. After each milestone, the Province will determine whether or not work will continue.</span></span></p><h2>Acceptance Criteria</h2><p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;">&nbsp;</p>
<ul style="box-sizing: border-box; margin-top: 0pt; margin-bottom: 0pt;">
<li><strong><span style="font-size: 14.6667px; white-space: pre-wrap;">Work with our </span>Agile/Scrum team (1012 Douglas Street in Victoria, BC):</strong>
<ul>
<li>The BC Developers' Exchange team works in 2-week sprints. You will attend planning (2 hours) and review (3 hours) meetings for each sprint.&nbsp; Developers from outside the Victoria area may attend by teleconference.</li>
<li>You will track your work with the team on our BC Developers' Exchange scrum board</li>
</ul>
</li>
</ul>
<ul style="box-sizing: border-box; margin-top: 0pt; margin-bottom: 0pt;">
<li><strong>Milestone 1</strong>
<ul>
<li>Review the exisiting REST API for the BC Developers' Exchange application</li>
<li>Prepare a report including the following elements<span style="font-family: Calibri; font-size: 14.6667px; white-space: pre;">&nbsp;</span>
<ul>
<li>Current state of API</li>
<li>Prioritized list of recommended improvements to API</li>
</ul>
</li>
<li>For each recommended improvement:
<ul>
<li>Identify the improvement</li>
<li>State the business case for the improvement</li>
<li>Estimate the time required to implement the improvement (in days or hours)</li>
</ul>
</li>
</ul>
</li>
<li><strong>Milestone 2</strong>
<ul>
<li>Document the API using Django REST Swagger</li>
<li>Write automated tests for our Jenkins pipeline in Postman/Newman</li>
<li>Submit pull requests for review/acceptance</li>
</ul>
</li>
<li><strong>Milestone 3</strong>
<ul>
<li>Meet with the Product Manager, Scrum Master and Lead Developer to review proposed improvements</li>
<li>Implement a mutually agreed upon number of improvements</li>
</ul>
</li>
</ul>
<p>&nbsp;</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-improvements-to-bcdevexchange-rest-api">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Thursday, March 8, 2018</b>.</p><p>We plan to assign this opportunity by <b>Saturday, March 10, 2018</b> with work to start on <b>Monday, March 12, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;">&nbsp;</p>
<ul style="box-sizing: border-box; margin-top: 0pt; margin-bottom: 0pt;">
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Your approach to completing the Acceptance Criteria (30 points).</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Your prior experience writing APIs and JavaScript-based applications (30 points).</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Your expertise in our technology stack (see Required skills) and experience contributing code to public code repositories (20 points).</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #333333; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To qualify for assignment your proposal must meet a minimum pass rate of 80% (Mandatory).</span></li>
</ul>

**Comment by SteveChapmanBCDX** [comment]
Hello everyone, and welcome to our latest opportunity!  Please let me know if you have any questions.

**Comment by Sybrand** [comment]
@SteveChapmanBCDX @ccoldwell : milestone 2 states that the documentation of the API is to be realised using Django. By that, would I be correct in assuming that the expectation is to _re-create_ the models already defined in JavaScript again in Python?

If this is the case, is there a specific reason for spinning up a Django instance to run in parallel with the existing Angular project? 

Would it not also make sense to consider generating API documentation from the JavaScript using reflection and code annotations? That way one would be spared having to make changes in two different projects when making any changes to the API, and reduce the risk of the documentation not matching up with the implementation.

**Comment by scchapma** [comment]
@Sybrand:  Thanks for your questions.  With respect to the API documentation, what we need is a Swagger definition.  However you choose to produce that is up to you.

On that basis, let me expressly answer your questions:

1.  For milestone 2, the API shall be documented using Swagger (vice "Django REST Swagger").  
2.  No skill in Django or Python is assumed or required.
3.  You can use any method of generating API documentation, so long as you deliver a Swagger definition.

Thanks for your interest, and let me know if you need additional information.

**Comment by madhavmalhotra3089** [comment]
Hi. One query. On the BC Dev exchange page, it says the opportunity is till Wednesday and over here it says till Thursday.

Could you please confirm the deadline. @SteveChapmanBCDX

**Comment by SteveChapmanBCDX** [comment]
@madhavmalhotra3089: The deadline is Wednesday (March 7) at 4:00 pm Pacific time.

**Comment by SteveChapmanBCDX** [comment]
@madhavmalhotra3089:  Thanks for bringing that ambiguity to our attention.  I have written up a bug report to fix the issue.

**Comment by ccoldwell** [comment]
This opportunity has been assigned

**Comment by scchapma** [comment]
Thanks to everyone for their fine submissions.  The opportunity has been awarded to @tiffanytangt. 

If you bid and would like a debrief, please contact me.
