### ISSUE TITLE
BC DevExchange Application - Automated Functional Tests

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#252]
Value: $10,000.00Closes: Wednesday, March 14, 2018Location: Victoria In-person work NOT required<h2>Opportunity Description</h2><p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">The BC Developers' Exchange application allows government actors to post opportunities that may be bid on by developers throughout British Columbia and beyond.</span></p>
<p><span style="background-color: transparent; font-family: Calibri; font-size: 11pt; white-space: pre-wrap;">We would like to make several focused improvements to improve the application's testing suites. </span></p>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;"><span style="font-family: Calibri;"><span style="font-size: 14.6667px; white-space: pre-wrap;">Specifically, we want to extend our automated test suites for functional and regression testing of the following application workflows for Code With Us (CWU) and Sprint With Us (SWU):</span></span></p>
<ul>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="white-space: pre-wrap;">CWU - Creating RFP</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="white-space: pre-wrap;">CWU - Creating RFP response</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="white-space: pre-wrap;">CWU - Notifying BC Developers' Exchange community</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="white-space: pre-wrap;">CWU - Assigning CWU RFP</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="white-space: pre-wrap;">SWU - Satisfying the requirements of the RFQ</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="white-space: pre-wrap;">SWU - Submitting company profile</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="white-space: pre-wrap;">SWU - Submitting individual profile</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="white-space: pre-wrap;">SWU - Creating RFP (government actor)</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="white-space: pre-wrap;">SWU - Creating RFP response</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="white-space: pre-wrap;">SWU - Creating evaluation view</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre;"><span style="white-space: pre-wrap;">SWU - Scoring questions/interview/pricing/skills</span></li>
</ul>
<p><span style="white-space: pre-wrap;"><span style="font-family: Calibri; font-size: 14.6667px;">We recommend you review the following information regarding our existing tests:</span></span></p>
<ul>
<li>https://github.com/BCDevExchange/devex/tree/develop/functional-tests</li>
<li>https://github.com/BCDevOps/BDDStack</li>
</ul>
<p>&nbsp;</p><h2>Acceptance Criteria</h2><p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;">&nbsp;</p>
<ul style="box-sizing: border-box; margin-top: 0pt; margin-bottom: 0pt;">
<li><strong><span style="font-size: 14.6667px; white-space: pre-wrap;">Work with our </span>Agile/Scrum team (1012 Douglas Street in Victoria, BC):</strong>
<ul>
<li>The BC Developers' Exchange team works in 2-week sprints. You will attend planning (2 hours) and review (3 hours) meetings for each sprint.&nbsp; Developers from outside the Victoria area may attend by teleconference.</li>
<li>You will track your work with the team on our BC Developers' Exchange scrum board</li>
</ul>
</li>
</ul>
<ul style="box-sizing: border-box; margin-top: 0pt; margin-bottom: 0pt;">
<li><strong>Development of Testing Suites</strong><br />
<ul>
<li>Meet with the Product Manager, Scrum Master and Lead Developer to review existing testing suites</li>
<li>In concert with Scrum Master and Lead Developer, determine required functional and regression test suites</li>
<li>Design and implement functional and regression test suites (automated, where possible).</li>
</ul>
</li>
</ul>
<p>&nbsp;</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-bc-devexchange-application---focused-improvements">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Wednesday, March 14, 2018</b>.</p><p>We plan to assign this opportunity by <b>Friday, March 16, 2018</b> with work to start on <b>Monday, March 19, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p style="box-sizing: border-box; margin: 0px 0px 10px; color: #333333; font-family: Yantramanav, sans-serif; font-size: 15px;">&nbsp;</p>
<ul style="box-sizing: border-box; margin-top: 0pt; margin-bottom: 0pt;">
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Your approach to completing the Acceptance Criteria (30 points).</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Your prior experience writing automated tests for JavaScript-based applications (30 points).</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Your expertise in our technology stack (see "Required Skills") and experience contributing code to public code repositories (20 points).</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #333333; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To qualify for this assignment your proposal must meet a minimum pass rate of 80% (Mandatory).</span></li>
<li dir="ltr" style="box-sizing: border-box; list-style-type: disc; font-size: 11pt; font-family: Calibri; color: #000000; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri; color: #333333; background-color: transparent; font-weight: 400; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">To qualify for this assignment you must complete the </span>Acceptance Criteria on or before March 31, 2018 (Mandatory)</li>
</ul>

**Comment by scchapma** [comment]
Hello everyone - we are excited to post our latest opportunity.  If you have any questions, please let me know.

**Comment by SteveChapmanBCDX** [comment]
Question from bidder:  "Milestone 1 mentions fixing bugs. Is that fixing automation bugs, or code bugs?"

Answer:  Milestone means fixing code bugs, not automation bugs.  Specifically, it means fixing existing bugs with the Code With Us and Sprint With Us code bases.

**Comment by SteveChapmanBCDX** [comment]
Hello everyone - we decided to republish this opportunity.  We have removed the original milestones 1 and 2 (testing and DevOps modifications).  The opportunity is now limited to the original milestone #3 - Functional and regression testing suites.

We look forward to your applications, and please let me know if you have any questions.

**Comment by scchapma** [comment]
Question from bidder: "Is there a specific proposal template we need to use?"

Answer:  No, there is no specific template that must be used.  However, we recommend that you keep the acceptance criteria in mind when you prepare your proposals.

**Comment by ccoldwell** [comment]
This opportunity has been assigned

**Comment by mark-a-wilson** [comment]
Hi Everyone,
Thanks you for your proposals. We have scored them by our evaluation criteria and **Robert Johnstone** scored the highest. 

Unsuccessful applicants, you can contact me directly (email address in my profile) if you'd like feedback.

**Comment by scchapma** [comment]
Contract complete, closing this issue.
