### ISSUE TITLE
Change Terms boilerplate info on Opportunity detail

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#26]
move Terms boilerplate text to display below Acceptance Criteria section

Change text to:
**Terms**
This is a fixed price opportunity governed by the terms of our lightweight procurement model, Code With Us. Read more to understand how it works.

**Comment by ccoldwell** [comment]
Made changes as specified but this does seem vague.  Read more of what?

**Comment by mark-a-wilson** [comment]
Read more will need a link to the Code With Us static content page (to be created).
