### ISSUE TITLE
DevOps Upgrades and Bug Fixes

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#260]
<p>This is a paid opportunity through the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><br/><p>To apply, visit the <a href="https://bcdevexchange.org/opportunities/cwu/opp-devops-upgrades-and-bug-fixes">opportunity page</a> and submit a proposal before Wednesday, March 14, 2018</p>

**Comment by SteveChapmanBCDX** [comment]
Hello everyone - we are excited to post our latest opportunity. If you have any questions, please let me know.

**Comment by bdwong** [comment]
Hi @SteveChapmanBCDX,

Are the priority bugs the ones marked as **priority**  under the issues section, or are they tracked internally by the team?

**Comment by SteveChapmanBCDX** [comment]
@bdwong:  The priority bugs are those identified as such in the Issues section.

**Comment by dwong-brighter** [comment]
Hi @SteveChapmanBCDX,

The payment page (https://github.com/BCDevExchange/code-with-us/wiki/4.-Payment) states that we can add GST on top of the fixed price if our business normally charges GST.  What about PST?  Does the winner of this opportunity need to charge/collect PST too?

**Comment by mark-a-wilson** [comment]
Hi all,
I'm the UX Designer for BCDevExchange. We received 4 proposals on this opportunity and have finished our evaluation: 

Congrats, @amanji on being the highest-scoring applicant! We look forward to working with you. 

Other applicants: thank you for taking the time and for the solid proposals. Please apply on future opportunities. If you'd like feedback, please feel free to contact me via the email address in my profile.
