### ISSUE TITLE
Can't save CWU opportunity

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#262]
This occurred on platform-dev between 10:45-10:55am March 12, 2018:

As admin
When I start creating a new CWU opportunity
And fill in all of the required fields on all the tabs
When I click on the SAVE CHANGES button nothing happens (the opportunity does not save)

**Comment by scchapma** [comment]
@mark-a-wilson:  Does this also happen in Production, or only in Dev?

**Comment by ccoldwell** [comment]
can this be put into jira?

**Comment by mark-a-wilson** [comment]
@scchapma Production is fine. I just tested.

**Comment by mark-a-wilson** [comment]
Closing issue, it's probably obsolete now.
