### ISSUE TITLE
Cassie's Gold

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#264]
Value: $0.00Closes: Tuesday, March 13, 2018Location: Vancouver Some in-person work required<h2>Opportunity Description</h2><p>ttt</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-txt">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Tuesday, March 13, 2018</b>.</p><p>We plan to assign this opportunity by <b>Tuesday, March 13, 2018</b> with work to start on <b>Tuesday, March 13, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
This is a test.
