### ISSUE TITLE
(TEST) Team needed to build app for YMCA

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#266]
Value: $0.00Closes: Wednesday, April 4, 2018Location: Victoria Some in-person work required<h2>Opportunity Description</h2><p>We've done user research and here's what we know...</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp--test--team-needed-to-build-app-for-ymca">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Wednesday, April 4, 2018</b>.</p><p>We plan to assign this opportunity by <b>Wednesday, April 11, 2018</b> with work to start on <b>Thursday, March 15, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
This was a test
