### ISSUE TITLE
Mines Digital Services

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#291]
Value: $0.00Closes: Monday, March 26, 2018Location: Victoria Some in-person work required<h2>Opportunity Description</h2><p><span style="font-family: 'Open Sans', Arial, sans-serif; text-align: justify;">Etiam luctus lacus a nulla aliquam, eu auctor quam pulvinar. Sed eros mauris, accumsan non eleifend vitae, imperdiet eu ex. In tempus, dolor vitae viverra vehicula, nulla quam congue dui, in accumsan dolor ex vitae eros. Aliquam fermentum ligula ut purus faucibus, vel varius lectus imperdiet. Nam sodales porta faucibus.&nbsp;</span></p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-fef">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Monday, March 26, 2018</b>.</p><p>We plan to assign this opportunity by <b>Friday, April 6, 2018</b> with work to start on <b>Friday, March 23, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
This is a test.
