### ISSUE TITLE
We need a great team

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#296]
Value: $0.00Closes: Monday, March 26, 2018Location: Victoria In-person work required<h2>Opportunity Description</h2><p>Blah blah blah</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-we-need-a-great-team">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Monday, March 26, 2018</b>.</p><p>We plan to assign this opportunity by <b>Monday, March 26, 2018</b> with work to start on <b>Monday, March 26, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
This was a test.
