### ISSUE TITLE
Testing Platform-Test after a long hiatus

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#297]
Value: $2,000.00Closes: Tuesday, March 27, 2018Location: Barriere In-person work NOT required<h2>Opportunity Description</h2><p>asdafsdf</p><h2>Acceptance Criteria</h2><p>1. this</p>
<p>2. this</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-testing-platform-test-after-a-long-hiatus">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Tuesday, March 27, 2018</b>.</p><p>We plan to assign this opportunity by <b>Tuesday, March 27, 2018</b> with work to start on <b>Tuesday, March 27, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>1. this (20 points)</p>
<p>2. this (30 points)</p>

**Comment by ccoldwell** [comment]
This opportunity has been assigned

**Comment by mark-a-wilson** [comment]
This was a test.
