### ISSUE TITLE
Can I view proposal content?

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#298]
Value: $2,000.00Closes: Monday, March 26, 2018Location: Armstrong In-person work NOT required<h2>Opportunity Description</h2><p>This is a test</p><h2>Acceptance Criteria</h2><p>1. this</p>
<p>2. that</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-can-i-view-proposal-content-">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Monday, March 26, 2018</b>.</p><p>We plan to assign this opportunity by <b>Tuesday, March 27, 2018</b> with work to start on <b>Tuesday, March 27, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>1. this (20 points)</p>
<p>2. that (30 points)</p>

**Comment by mark-a-wilson** [comment]
This was a test.
