### ISSUE TITLE
Testing Platform-Test Part 2

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#299]
Value: $0.00Closes: Tuesday, March 27, 2018Location: Armstrong In-person work NOT required<h2>Opportunity Description</h2><p>yes</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-testing-platform-test-part-2">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Tuesday, March 27, 2018</b>.</p><p>We plan to assign this opportunity by <b>Tuesday, March 27, 2018</b> with work to start on <b>Tuesday, March 27, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
This was a test.
