### ISSUE TITLE
(TEST) Redesign Victoria's Downtown YMCA

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#300]
Value: $0.00Closes: Tuesday, April 10, 2018Location: Victoria Some in-person work required<h2>Opportunity Description</h2><p>We've been needing to do this for a long time.</p>
<p>What we know from surveys and user research is that people primarily want:</p>
<p>1.&nbsp;</p>
<p>2.&nbsp;</p>
<p>3.&nbsp;</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp--test--redesign-victoria-s-downtown-ymca">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Tuesday, April 10, 2018</b>.</p><p>We plan to assign this opportunity by <b>Friday, April 20, 2018</b> with work to start on <b>Thursday, March 29, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
This was a test.
