### ISSUE TITLE
(TEST) Mark's SWU Opportunity

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#301]
Value: $0.00Closes: Friday, March 30, 2018Location: Abbotsford Some in-person work required<h2>Opportunity Description</h2><p>sd</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp--test--mark-s-swu-opportunity">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Friday, March 30, 2018</b>.</p><p>We plan to assign this opportunity by <b>Wednesday, April 4, 2018</b> with work to start on <b>Thursday, March 29, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
This was a test.
