### ISSUE TITLE
CC2

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#304]
Value: $4,500.00Closes: Thursday, March 29, 2018Location: Port Alberni Some in-person work required<h2>Opportunity Description</h2><p>b</p><h2>Acceptance Criteria</h2><p>d</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-cc2">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Thursday, March 29, 2018</b>.</p><p>We plan to assign this opportunity by <b>Thursday, March 29, 2018</b> with work to start on <b>Thursday, March 29, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>d</p>

**Comment by mark-a-wilson** [comment]
This was a test.
