### ISSUE TITLE
New Opportnity

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#305]
Value: $0.00Closes: Monday, April 2, 2018Location: 100 Mile House Some in-person work required<h2>Opportunity Description</h2><p>asdf</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-new-opportnity">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Monday, April 2, 2018</b>.</p><p>We plan to assign this opportunity by <b>Monday, April 2, 2018</b> with work to start on <b>Monday, April 2, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
This was a test
