### ISSUE TITLE
(TEST) Ensure applicants can upload attachments to proposal

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#309]
Value: $1,000.00Closes: Wednesday, April 4, 2018Location: Castlegar Some in-person work required<h2>Opportunity Description</h2><p>asdf</p><h2>Acceptance Criteria</h2><p>1</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp--test--ensure-applicants-can-upload-attachments-to-proposal">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Wednesday, April 4, 2018</b>.</p><p>We plan to assign this opportunity by <b>Wednesday, April 4, 2018</b> with work to start on <b>Wednesday, April 4, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>1</p>

**Comment by mark-a-wilson** [comment]
This was a test.
