### ISSUE TITLE
Titel

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#316]
Value: $3,500.00Closes: Friday, April 13, 2018Location: Dawson Creek Some in-person work required<h2>Opportunity Description</h2><p>Background</p><h2>Acceptance Criteria</h2><p>AC</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-titel">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Friday, April 13, 2018</b>.</p><p>We plan to assign this opportunity by <b>Friday, April 13, 2018</b> with work to start on <b>Friday, April 13, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>PEC</p>

**Comment by mark-a-wilson** [comment]
This was a test.
