### ISSUE TITLE
Diana - can you see this opportunity

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#318]
Value: $500.00Closes: Monday, April 16, 2018Location: Barriere Some in-person work required<h2>Opportunity Description</h2><p>asdf</p><h2>Acceptance Criteria</h2><p>asdf</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-diana-can-you-see-this-opportunity">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Monday, April 16, 2018</b>.</p><p>We plan to assign this opportunity by <b>Monday, April 16, 2018</b> with work to start on <b>Monday, April 16, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>asdf</p>

**Comment by mark-a-wilson** [comment]
This was a test.
