### ISSUE TITLE
Fool's Gold

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#319]
Value: $0.00Closes: Monday, April 16, 2018Location: Victoria In-person work required<h2>Opportunity Description</h2><p>tttt</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-fool-s-gold">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Monday, April 16, 2018</b>.</p><p>We plan to assign this opportunity by <b>Monday, April 16, 2018</b> with work to start on <b>Monday, April 16, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
This was a test.
