### ISSUE TITLE
Remove fields from Create Program form

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#32]
- Owner (not sure what this is for?)
- Tags (not sure what we'd want the user to enter here?)

**Comment by ccoldwell** [comment]
owner was the ministry of government body that owned the program, I think it had a different name at one point.  I will remove, but perhaps we should revisit?

tags, just for searching, will comment out and we can use at a later date if we need

**Comment by mark-a-wilson** [comment]
Done - thanks
