### ISSUE TITLE
Death from Above 1979

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#320]
Value: $3,500.00Closes: Monday, April 16, 2018Location: Victoria In-person work required<h2>Opportunity Description</h2><p>ttt</p><h2>Acceptance Criteria</h2><p>ffff</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-death-from-above-1979">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Monday, April 16, 2018</b>.</p><p>We plan to assign this opportunity by <b>Monday, April 16, 2018</b> with work to start on <b>Monday, April 16, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>ffff</p>

**Comment by mark-a-wilson** [comment]
This was a test.
