### ISSUE TITLE
Mark should not get notified about this opportunity because he unsubscribed

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#323]
Value: $500.00Closes: Tuesday, April 17, 2018Location: 100 Mile House In-person work required<h2>Opportunity Description</h2><p>adf</p><h2>Acceptance Criteria</h2><p>asfd</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-mark-should-not-get-notified-about-this-opportunity-because-he-unsubscribed">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Tuesday, April 17, 2018</b>.</p><p>We plan to assign this opportunity by <b>Tuesday, April 17, 2018</b> with work to start on <b>Tuesday, April 17, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>asdf</p>

**Comment by mark-a-wilson** [comment]
This was a test.
