### ISSUE TITLE
Show me the money in my email

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#325]
Value: $0.00Closes: Wednesday, April 18, 2018Location: Victoria Some in-person work required<h2>Opportunity Description</h2><p>ttt</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-show-me-the-money-in-my-email">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Wednesday, April 18, 2018</b>.</p><p>We plan to assign this opportunity by <b>Wednesday, April 18, 2018</b> with work to start on <b>Wednesday, April 18, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
This was a test.
