### ISSUE TITLE
Testing "New Opportunity" email notification template

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#326]
Value: $3,000.00Closes: Wednesday, April 18, 2018Location: Vancouver Some in-person work required<h2>Opportunity Description</h2><p>asdf</p><h2>Acceptance Criteria</h2><p>sf</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-testing-new-opportunity--email-notification-template">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Wednesday, April 18, 2018</b>.</p><p>We plan to assign this opportunity by <b>Wednesday, April 18, 2018</b> with work to start on <b>Wednesday, April 18, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>sf</p>

**Comment by mark-a-wilson** [comment]
This was a test.
