### ISSUE TITLE
New opportunity in Staging

### ISSUE THREAD

**Issue by ccoldwell** [BCDevExchange/devex#327]
Value: $1,500.00Closes: Wednesday, April 18, 2018Location: Campbell River In-person work NOT required<h2>Opportunity Description</h2><p>:LKjla;skdjfl;kasjdl;fkjasl;dkfj</p><h2>Acceptance Criteria</h2><p>Apply</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-new-opportunity-in-staging">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Wednesday, April 18, 2018</b>.</p><p>We plan to assign this opportunity by <b>Wednesday, April 18, 2018</b> with work to start on <b>Wednesday, April 18, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>if you've applied, you win</p>

**Comment by mark-a-wilson** [comment]
This was a test.

**Comment by bcdevex** [comment]
This opportunity has been assigned
