### ISSUE TITLE
April 18 Tester

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#328]
Value: $4,500.00Closes: Wednesday, April 18, 2018Location: Comox Some in-person work required<h2>Opportunity Description</h2><p>Background</p><h2>Acceptance Criteria</h2><p>AC</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-april-18-tester">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Wednesday, April 18, 2018</b>.</p><p>We plan to assign this opportunity by <b>Wednesday, April 18, 2018</b> with work to start on <b>Wednesday, April 18, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>PEC</p>

**Comment by mark-a-wilson** [comment]
This was a test.
