### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#331]
Value: $11,000.00Closes: Thursday, April 19, 2018Location: Clearwater Some in-person work required<h2>Opportunity Description</h2><p>Back</p><h2>Acceptance Criteria</h2><p>AC</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-title3">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Thursday, April 19, 2018</b>.</p><p>We plan to assign this opportunity by <b>Thursday, April 19, 2018</b> with work to start on <b>Thursday, April 19, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>PEC123</p>

**Comment by mark-a-wilson** [comment]
This was a test.
