### ISSUE TITLE
Testing email notifications

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#332]
Value: $0.00Closes: Thursday, April 19, 2018Location: Vancouver In-person work NOT required<h2>Opportunity Description</h2><p>asdf</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-testing-email-notifications">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Thursday, April 19, 2018</b>.</p><p>We plan to assign this opportunity by <b>Thursday, April 19, 2018</b> with work to start on <b>Thursday, April 19, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
This was a test.
