### ISSUE TITLE
Duke's Done

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#333]
Value: $4,000.00Closes: Thursday, April 19, 2018Location: Victoria In-person work required<h2>Opportunity Description</h2><p>The great American novel</p><h2>Acceptance Criteria</h2><p>Pine &amp; cedar</p><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-duke-s-done">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Thursday, April 19, 2018</b>.</p><p>We plan to assign this opportunity by <b>Thursday, April 19, 2018</b> with work to start on <b>Thursday, April 19, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2><p>Steal Duke's timber</p>

**Comment by mark-a-wilson** [comment]
This was a test.
