### ISSUE TITLE
Can your company start and submit a proposal on this if it doesn't meet the RFQ requirements

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#335]
Value: $0.00Closes: Tuesday, April 24, 2018Location: Abbotsford Some in-person work required<h2>Opportunity Description</h2><p>asdf</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-can-your-company-start-and-submit-a-proposal-on-this-if-it-doesn-t-meet-the-rfq-requirements">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Tuesday, April 24, 2018</b>.</p><p>We plan to assign this opportunity by <b>Friday, April 27, 2018</b> with work to start on <b>Thursday, April 19, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
This was a test.
