### ISSUE TITLE
For Loren - Apr 23

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#336]
Value: $0.00Closes: Wednesday, April 25, 2018Location: Victoria In-person work required<h2>Opportunity Description</h2><p>Some background</p><h2>Acceptance Criteria</h2><h2>How to Apply</h2><p>Go to the <a href="https://bcdevexchange.org/opportunities/opp-for-loren---apr-23">Opportunity Page</a>, click the Apply button above and submit your proposal by 16:00 PST on Wednesday, April 25, 2018</b>.</p><p>We plan to assign this opportunity by <b>Monday, April 30, 2018</b> with work to start on <b>Monday, April 23, 2018</b>.</p><h2>Proposal Evaluation Criteria</h2>

**Comment by mark-a-wilson** [comment]
This was a test.
