### ISSUE TITLE
Testing CWU notification

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#339]
<p>This is a paid opportunity through the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><br/><p>To apply, visit the <a href="https://bcdevexchange.org/opportunities/cwu/opp-testing-cwu-notification">opportunity page</a> and submit a proposal before Wednesday, April 25, 2018</p>

**Comment by mark-a-wilson** [comment]
This was a test.
