### ISSUE TITLE
Test Accepting SWU RFQ in Company Profile

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#340]
<p>This is a paid opportunity through the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><br/><p>To apply, visit the <a href="https://bcdevexchange.org/opportunities/swu/opp-test-accepting-swu-rfq-in-company-profile">opportunity page</a> and submit a proposal before Wednesday, April 25, 2018</p>

**Comment by mark-a-wilson** [comment]
This was a test.
