### ISSUE TITLE
Rommel's Dream

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#342]
<p>This is a paid opportunity through the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><br/><p>To apply, visit the <a href="https://bcdevexchange.org/opportunities/swu/opp-rommel-s-dream">opportunity page</a> and submit a proposal before Wednesday, May 30, 2018</p>

**Comment by mark-a-wilson** [comment]
This is a test.
