### ISSUE TITLE
April 27 - 1530

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#344]
<p>This is a paid opportunity through the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><br/><p>To apply, visit the <a href="https://bcdevexchange.org/opportunities/swu/opp-april-27---1530">opportunity page</a> and submit a proposal before Tuesday, May 1, 2018</p>

**Comment by mark-a-wilson** [comment]
This was a test.
