### ISSUE TITLE
Testing the scoring matrix

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#346]
<p>This is a paid opportunity through the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><br/><p>To apply, visit the <a href="https://bcdevexchange.org/opportunities/swu/opp-testing-the-scoring-matrix">opportunity page</a> and submit a proposal before Sunday, April 29, 2018</p>

**Comment by paulroberts68** [comment]
This is a test
