### ISSUE TITLE
Test Opportunity

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#357]
<p>This is a paid opportunity through the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><br/><p>To apply, visit the <a href="https://bcdevexchange.org/opportunities/swu/opp-test-opportunity">opportunity page</a> and submit a proposal before Thursday, May 31, 2018</p>

**Comment by mark-a-wilson** [comment]
Hello everyone. I am the product manager for this opportunity. If you have any questions please post them and I'll respond here for all to see. If you need to ask a question but don't want others to see that you're interested in this opportunity, you can email me at mark.wilson@gov.bc.ca. I will then anonymize your question and post it along with an answer. 

Thanks for your interest!
