### ISSUE TITLE
Fix layout of Sign Up screen 

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#36]
IMO, we should remove:

- From header: Top nav, Sign Up and Sign In buttons, (leave BCDevExchange logo)
- Footer

**Comment by ccoldwell** [comment]
this would actually be quite difficult as the view that the signup form in on is nested within the other views, so turning off a parent view based on a child view is tricky

**Comment by mark-a-wilson** [comment]
layout is fine now
