### ISSUE TITLE
Test CWU Opp

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#366]
<p>This is a paid opportunity through the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><br/><p>To apply, visit the <a href="https://bcdevexchange.org/opportunities/cwu/opp-test-cwu-opp">opportunity page</a> and submit a proposal before Thursday, May 31, 2018</p>

**Comment by mark-a-wilson** [comment]
This was a test.
