### ISSUE TITLE
Testing email notification of new opportunity

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#367]
<p>This is a paid opportunity through the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><br/><p>To apply, visit the <a href="https://bcdevexchange.org/opportunities/cwu/opp-testing-email-notification-of-new-opportunity">opportunity page</a> and submit a proposal before Monday, May 14, 2018</p>

**Comment by mark-a-wilson** [comment]
This was a test.
