### ISSUE TITLE
Test email notification content

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#383]
<p>This is a paid opportunity through the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><br/><p>To apply, visit the <a href="https://bcdevexchange.org/opportunities/cwu/opp-test-email-notification-content">opportunity page</a> and submit a proposal before Friday, June 22, 2018</p>

**Comment by mark-a-wilson** [comment]
This was a test.
