### ISSUE TITLE
BA-614 // Uploading reference documents are timing out

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#399]
(Originally reported by @SteveChapmanBCDX:)

When I attempt to upload a large document using the upload feature in SWU's "References" tab, I am not able to load large documents. The upload times out after 30 seconds and gives me the following 504 error message:

![screen shot 2018-05-17 at 8 53 12 am](https://user-images.githubusercontent.com/16946297/41988077-ea5ed268-79ef-11e8-8916-c4b7e7ffb0d5.png)

Initially, I received a toast indicating that the file had been successfully uploaded. However, that was not the case. I have filed this bug as a separate issue.

**Comment by sutherlanda** [comment]
This issue has been resolved.
