### ISSUE TITLE
draft - Opportunity creation, assignment and display

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#4]
Background

bcdevexchange.org is experimenting with a public/private collaboration framework called Code With Us where government program owners are able to post coding and other digital based opportunities.

During this iteration the BC Developers' Exchange is creating a better way for government program owners to create Code With Us opportunities, provide work context and facilitate collaboration. This work is related to issue 32.

Story

As a government program lead (owner) I need to be able to create an opportunity that relates to a project (displayed in the BC DevEx app) so that I can advertize the opportunity using the Code With Us Mechanism.

How to contribute

We are offering this issue as a paid opportunity through our experimental procurement model, Code-with-Us.

To work on this issue, we are accepting proposals until 5:00 PM on Friday, October 28, 2016. After that time, we will evaluate the proposals we’ve received, and assign the work to one person on Monday, October 31. How assignment works

What to include in your proposal

We will evaluate and score proposals by the following criteria:

Your ability to dedicate the time needed to complete the issue by November 10, 2016 (Mandatory).
The estimated date you think you can show us your first iteration (Mandatory).
A short (no more than 200 words) summary of your proposed approach (60 points).
References to your relevant experience and demonstrated ability to do the work (40 points). For example, a link to your GitHub projects.
With your proposal, you must attach a copy of the Code-with-Us Terms, with the required information asked for in the “Acceptance” section of the Terms inserted into the document (Mandatory).
The highest scoring proposal will get the assignment.

How to submit your proposal

Please submit your proposal to Meaghan.Stewart@gov.bc.ca before 5:00 PM on Friday, October 28, 2016. Please put "A program owner needs to be able to sign-up to the BC Developers' Exchange" in the subject line.

Acceptance Criteria

To be paid for this opportunity we need you to:
Work with the BC DevEx UX team to refine their process design wireframes or composites
The creation of the opportunity will occur in the DevEx app
The opportunity needs to be related to a program project
An issue in GitHub needs to be created simultaneously
The user needs a wizard function to help them create the opportunity
Work with the BC DevEx UX team to refine their process design wireframes or composites
User can assign the opportunity
User can issue a value to the opportunity; see the BCDevExchange [Code-with-Us] page (https://bcdevexchange.org/developers/)
User can put a deadline on the opportunity
A deadline appears on the GitHub issue simultaneously
User can add skills required to an opportunity; see the BCDevExchange [Code-with-Us] page (https://bcdevexchange.org/developers/)
User can "post" the opportunity in a gid similar to the BCDevExchange [Code-with-Us] page (https://bcdevexchange.org/developers/)
The opportunity will be displayed in three states "open" "in-progress" and "closed"
Assume that the user does not have a Github account
After you perform the requested changes, we will accept your work and pay.

How payment works

Questions, Comments, Suggestions?

**Comment by mark-a-wilson** [comment]
Closing this issue....looks like it was a draft prior to creating https://github.com/BCDevExchange/devex/issues/9 ?
