### ISSUE TITLE
BA-615 // User not notified of pending upload

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#400]
(Originally reported by @SteveChapmanBCDX:)

In SWU, the "References" tab includes an upload feature. When I upload a document, I am notified immediately that the upload was "successful" even when the upload is pending and has not completed. This is a problem, as I noted in BA-614 that some files are not uploading properly. However, the user does not receive notice of the failure until the upload has timed out (30 seconds after upload). In the meantime, the user may have navigated away from the page.

Let's fix this so that the user receives notice of pending uploads.

**Comment by sutherlanda** [comment]
This issue has been resolved.
