### ISSUE TITLE
Add Word Count for Proposal text

### ISSUE THREAD

**Issue by bdwong** [BCDevExchange/devex#416]
I'd like to suggest that the proposal text field for an opportunity should include a word count widget so that applicants can see if their proposal has grown too big. This is relevant if there is a word limit on the proposal (as on recent proposals.)

**Comment by mark-a-wilson** [comment]
Thanks Brian - yes, a very obvious improvement we should make.

**Comment by sutherlanda** [comment]
This suggestion has been implemented as a feature on both CWU and SWU opportunities.  Thanks @bdwong .  Closing this issue as complete.
