### ISSUE TITLE
Display problem after install

### ISSUE THREAD

**Issue by clauded** [BCDevExchange/devex#417]
I'm trying to install BCDevExchange for testing. I followed installation instructions of README.md (develop branch) and when I go to home page (localhost:3030), display is garbled as if there's a wrong stylesheet:

https://i.imgur.com/WPhiCPh.png

**Comment by sutherlanda** [comment]
Hi Claude,

I'm not able to reproduce this issue, but I would suggest trying the following:

- Re-run the `setup.sh` script
- If it fails on the `RUN bower...` step, comment that line out of the docker file and then re-run `setup.sh`
- Once complete, run `dev.sh` to launch the devex docker container
- Run the following from within the container: `bower install --allow-root`
- Run `npm run quiet` to run the devex server and try to hit localhost:3030 again

We've found that bower has become inconsistent during the setup process, and we are in the midst of removing it completely from the build. 

Hopefully, this fixes the display issue you are experiencing.  If not, please let me know by replying here and I can gather some more info from you.

Andrew

**Comment by clauded** [comment]
Runs fine now after following your instructions. Thanks!
