### ISSUE TITLE
Test Opportunity for CWU Demo

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#434]
<p>This issue has been auto-generated to facilitate questions about <a href="https://bcdevexchange.org/opportunities/cwu/opp-test-opportunity-for-cwu-demo">a paid opportunity</a> that has just been posted on the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-test-opportunity-for-cwu-demo">visit the opportunity page</a>. The opportunity closes on <b>Wednesday, August 15, 2018</b>.</p>

**Comment by mark-a-wilson** [comment]
This was a test.
