### ISSUE TITLE
Test the link in the "Got Questions?" box

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#458]
<p>This issue has been auto-generated to facilitate questions about <a href="https://bcdevexchange.org/opportunities/cwu/opp-test-the-link-in-the--got-questions---box">a paid opportunity</a> that has just been posted on the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-test-the-link-in-the--got-questions---box">visit the opportunity page</a>. The opportunity closes on <b>Wednesday, September 5, 2018</b>.</p>

**Comment by mark-a-wilson** [comment]
this was a test
