### ISSUE TITLE
Run-time JavaScript error: Unable to start a proposal

### ISSUE THREAD

**Issue by dhruvio** [BCDevExchange/devex#495]
I am unable to start a proposal by clicking on the "Start a Proposal" button. I experienced this issue when applying for [this opportunity](https://www.bcdevexchange.org/opportunities/cwu/opp-enhancements) on 2018.10.26 using Firefox with this user agent:

```
Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0
```

This was also reproducible on a recent version of Chrome.

The console outputted the following error message when I clicked the "Start a Proposal" button. Nothing happened in the UI.

```
Transition Rejection($id: 0 type: 6, message: The transition errored, detail: TypeError: deniedRoles is undefined) stateService.ts:533:6
```

I was able to workaround this issue by using the web inspector's JavaScript debugger to override the `deniedRoles` variable to an empty list. This prevented the run-time error, and allowed me to submit my proposal.

**Comment by SteveChapmanBCDX** [comment]
@dhruvio - Thanks for alerting us to this issue.  I'm glad to hear that you were able to submit your proposal.  Please let us know if you run into any further difficulties.

We're committing a change now to fix this issue.  The related JIra ticket is "BA-980".
