### ISSUE TITLE
Upgrades to Functional Testing Suite and Unit Testing Suite

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#530]
<p>This issue has been auto-generated to facilitate questions about <a href="https://bcdevexchange.org/opportunities/cwu/opp-upgrades-to-functional-testing-suite-and-unit-testing-suite">a paid opportunity</a> that has just been posted on the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-upgrades-to-functional-testing-suite-and-unit-testing-suite">visit the opportunity page</a>. The opportunity closes on <b>Saturday, December 15, 2018</b>.</p>

**Comment by sutherlanda** [comment]
Hi @mattcan, thanks for your question.  You are correct.  This opportunity is actually for updating the _functional test suite only_.  We had originally scoped the opportunity to include unit test and functional test updates, but we reduced the scope to functional tests only (and didn't update the opportunity title).

**Comment by bcdevex** [comment]
This opportunity has been assigned
