### ISSUE TITLE
Industrial GHG Reporting System Improvements: 404 pages

### ISSUE THREAD

**Issue by DaveJarvis** [BCDevExchange/devex#541]
1. Visit https://www.bcdevexchange.org/opportunities/swu/opp-industrial-ghg-reporting-database-improvements
1. Click **Climate Action Secretariat**

Browser directs to https://www.bcdevexchange.org/opportunities/swu/programs/pro-climate-action-secretariat with 404 not found.

Also:

1. Visit https://www.bcdevexchange.org/opportunities/swu/opp-industrial-ghg-reporting-database-improvements
1. Click **Industrial GHG Reporting System Improvements**

Browser directs to https://www.bcdevexchange.org/opportunities/swu/projects/prj-industrial-ghg-reporting-database-improvements with 404 not found.

**Comment by sutherlanda** [comment]
Hi @DaveJarvis , thanks for bring this issue to our attention.  It looks like this is a variation of a current issue with ui-router, described here: https://github.com/angular-ui/ui-router/issues/3728.  I've implemented the suggested workaround from that issue, and we should have that in production shortly.

**Comment by sutherlanda** [comment]
Yes, the issue lies in the ui-sref attribute of the link.  angular-ui-router is randomly adding on portions of an incorrect route to the generated href.

**Comment by sutherlanda** [comment]
This issue has been resolved.
