### ISSUE TITLE
Linking Github Account to BC Dev Exchange

### ISSUE THREAD

**Issue by marieanikparadis** [BCDevExchange/devex#548]
Hi,

I'm trying to link my GitHub Account to BC Dev Exchange and I am getting a 504 Gateway Time-out.

This is the URL it's hitting:
https://bcdevexchange.org/api/auth/github/callback?code=51e72dd25800c3aa174c

If I refresh the page, it redirects here:
https://bcdevexchange.org/authentication/signin?err=Something%20went%20wrong

I've tried several different browsers and rebooting and it doesn't seem to help. I did receive the prompt once to authorize BC Dev Exchange for OAuth. Tried revoking and reauthorizing but that didn't help.

**Comment by sutherlanda** [comment]
Hi @marieanikparadis , thanks for alerting us to this issue.  I believe I have resolved the problem.  Can you try to link your account again by hitting Sign-In on the Developer's Exchange site?  Let me know if you are still having issues.

**Comment by marieanikparadis** [comment]
Works now. Thanks for the help.
