### ISSUE TITLE
Fix layout and content of Member cards

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#57]
- image should be square
- Info should display: Name, Title/job/role (on the program or project), Email address

only value of showing members is to display helpful information (or link to their profile for more info)

**Comment by mark-a-wilson** [comment]
this related to https://github.com/BCDevExchange/devex/issues/83

**Comment by mark-a-wilson** [comment]
I think we agreed to this yesterday:
- When a user requests membership to a program or project, the admin for that program or project, upon confirming them as a member, enters a role for that user 
- Make the card display: Name, role, email address

**Comment by ccoldwell** [comment]
Upon reviewing how this could be implemented it turns out to be a lot more involved than one would think.  There are different ways to go about it, but all of them require new UI/UX and new backend configurations.

**Comment by mark-a-wilson** [comment]
Adding this to DevX App Trello board
