### ISSUE TITLE
Database Management Improvements for the BC Developers' Exchange

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/devex#576]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-database-improvements-for-the-bc-developers--exchange"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-database-improvements-for-the-bc-developers--exchange">visit the opportunity page</a>.
The opportunity closes on <b>Tuesday, March 19th, 2019 at 16:00 PDT</b>.</p>

**Comment by lucastetreault** [comment]
Hi, the opportunity mentions: 
> Update the existing database migration tools to be available as a configurable service in OpenShift

Are the existing database migrations tools included in this repository? The only mention I can find is in the [openshift readme](https://github.com/BCDevExchange/devex/tree/develop/openshift) section "h1. Data management operations" but that seems like it might just be some copy/pasted documentation.

**Comment by sutherlanda** [comment]
Thanks for your question @lucastetreault .  The existing database migration tools are not included in the main devex repo.  The existing tool that we have is a database scrubber, which can be viewed here: https://github.com/BCDevExchange/devexUtils/tree/master/scrubber.  This opportunity includes updating and extending this tool or possibly augmenting this tool with additional services or applications.

**Comment by lucastetreault** [comment]
Thanks @sutherlanda. I'll update my submitted proposal. I thought migration was referring to schema changes as opposed to backups/restores.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by sutherlanda** [comment]
Thank you to everyone who submitted proposals for this opportunity. We received a total of 7 proposals, and have assigned the opportunity. If you would like feedback on your proposal, please feel to request via email (address in my profile).

**Comment by mark-a-wilson** [comment]
Acceptance criteria was satisfied for this opportunity — see [commits by @chrisfosterelli in our devexUtils repo](https://github.com/BCDevExchange/devexUtils/commits?author=chrisfosterelli).
