### ISSUE TITLE
Link to BC Tech Summit on Homepage seems outdated

### ISSUE THREAD

**Issue by patricksimonian** [BCDevExchange/devex#578]
![Screen Shot 2019-03-27 at 2 26 04 PM](https://user-images.githubusercontent.com/21046727/55113429-759f3880-509c-11e9-84e3-e47fd1219f3b.png)

Not sure if it is there intentionally, but it seems outdated!

Just posting this issue as an fyi!

**Comment by mark-a-wilson** [comment]
Duly noted! Thanks Patrick.

**Comment by patricksimonian** [comment]
de nada!

**Comment by mark-a-wilson** [comment]
Forgot to close this issue upon https://github.com/BCDevExchange/devex/commit/5bf8ad6415decb74e6da99be6353d81b3821a512
