### ISSUE TITLE
Sign-in message

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#60]
At present the sign-in message reads "Sign in using your social accounts" however it should read "Sign in using GitHub"

**Comment by mark-a-wilson** [comment]
I'm not sure, but if Sign Up and Sign In are now both going to the same page, this is fixed under
https://github.com/BCDevExchange/devex/commit/3fc470e183a14fcb9cec9679798d72cab7225a98

**Comment by mark-a-wilson** [comment]
I think we'll call this done. "Sign In with your GitHub account", I think, works for both SIgn In and Sign Up.
