### ISSUE TITLE
Icon/Picture not showing in IE

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#61]
The icons for the program logo's and users are not showing in IE 11 (and so presumably in government EI instances).

**Comment by paulroberts68** [comment]
@ccoldwell looks like the file type is being stripped off. When we add .jpg to the file name it shows.

**Comment by watkinspd** [comment]
<img width="1135" alt="screen shot 2017-02-09 at 8 04 43 am" src="https://cloud.githubusercontent.com/assets/2670671/22791537/881524a0-ee9e-11e6-95d7-9f95cb25fbb4.png">

**Comment by ccoldwell** [comment]
strongly dislike IE

**Comment by mark-a-wilson** [comment]
fixed! way to go 👍
