### ISSUE TITLE
BCDX logo size

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#62]
The BCDX logo is not sizing correctly on the home page.

**Comment by paulroberts68** [comment]
@mark-a-wilson I have it on good authority that the pixel size is wrong. It's currently set at 50 and it should be 85. May be part of the problem.

**Comment by mark-a-wilson** [comment]
reverted back to 50px https://github.com/BCDevExchange/devex/commit/c48a8e40f67ba7479e903f5b03726e8c2b308ae3
