### ISSUE TITLE
Remove comma on Code With Us page

### ISSUE THREAD

**Issue by abronee** [BCDevExchange/devex#70]
Under **'Public Sector Product Managers'**:

Not critical, but the final comma isn't necessary in the first paragraph. Should read:
"Code With Us is a new way for the B.C. public sector to access talented developers and pay for code. Post an opportunity worth up to $10,000, evaluate proposals, choose a developer and get to work!"

**Comment by mark-a-wilson** [comment]
Done! (Sorry, I'm an oxford fan.) 😛
