### ISSUE TITLE
Profile picture won't show

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#82]
Logged in as admin and as a github user. Selected picture and received 'upload successful' message. Picture didn't show on profile.

**Comment by mark-a-wilson** [comment]
Here's what happened to me:
1st attempt: error message
2nd attempt: success message, but picture was lost
3rd attempt: same as 2nd attempt

**Comment by ccoldwell** [comment]
this one was tricky, found it though

**Comment by mark-a-wilson** [comment]
fixed - verified
