### ISSUE TITLE
Edit button on profile & opportunities doesn't work

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#84]
The pencil icon on the profile and opportunities page (top right of each box) doesn't work)

**Comment by mark-a-wilson** [comment]
it's working, it's just that the tooltip is getting in the way...I've removed them from program, project, and opportunity cards
https://github.com/BCDevExchange/devex/commit/d0d390d06091c45532bcfb01ed32717bec6364d9
