### ISSUE TITLE
Sign-up on Opportunities page not working

### ISSUE THREAD

**Issue by DavidR8** [BCDevExchange/devex#85]
Couldn't find another issue so maybe this is in progress?

**Comment by paulroberts68** [comment]
![image](https://cloud.githubusercontent.com/assets/11237533/22795898/2fb43c60-eead-11e6-8ff4-115d6eb16e4d.png)

**Comment by DavidR8** [comment]
The button is there however it is non-functional (on Firefox at least)

**Comment by mark-a-wilson** [comment]
fixed now https://github.com/BCDevExchange/devex/commit/25d76f4121cb828a41efed13e1c35cc50c0bd90e
