### ISSUE TITLE
Clicking Cancel on new program form caused "Page Not Found" screen

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#88]
Same error when clicking Cancel on on new project form. Context: I was logged in as Mark Wilson (not admin). Tried same actions logged in as admin, and no errors.

**Comment by ccoldwell** [comment]
fixed, caused by an unrelated error on the page that caused overall processing to fail

**Comment by mark-a-wilson** [comment]
complete!
