### ISSUE TITLE
Developing the BC Developers’ Exchange website front-end (BCDX-MTIC-004)

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#9]
# Paid Opportunity
We are offering a fixed price of $3,000 to complete the work described in this issue, according to the terms of our [experimental procurement model, Code-with-Us](https://github.com/BCDevExchange/code-with-us/wiki/1.-Intro-&-Disclaimer).

[Here’s how payment works](https://github.com/BCDevExchange/code-with-us/wiki/5.-How-payment-works)

## Background
[bcdevexchange.org](https://bcdevexchange.org/) is the public facing site for the BC Developers' Exchange - an experiment in tech innovation and collaboration.

You can find the code for the theme [here](https://github.com/BCDevExchange/design). We want to apply our new theme and design templates to the code already built for the [site](https://github.com/BCDevExchange/devex) and deliver the following functionality:

## User Story
As a government program owner I need to be able to navigate through a series of self-service screens on bcdevexchange.org to:
1. Sign Up
2. Create a page that describes my government’s **program**
3. Create a page that describes my program’s **project**
4. Create a page that describes a **work opportunity** for my program’s project
5. View a page of Resources that are available to me

## Acceptance Criteria
To be paid for this opportunity, you will:

1. Participate as a part of our team’s sprint planning workshop from **10:00 AM - 12:00 PM on December 16, 2016 at 1012 Douglas Street in Victoria, BC**.
2. Spend a minimum of **2 hours** per weekday (Monday - Friday, excluding holidays, between the hours of 8:30 AM and 5:00 PM) working in person with us at our office (1012 Douglas Street in Victoria, BC) for the duration of your work. We want you to work side-by-side with our lead developer and designer to apply the the new theme and deliver the desired functionality in our dev environment. 
3. Deliver a functioning presentation layer for bcdevexchange.org that includes all of the following:
- Homepage
- Resources page
- Program list page
- Program detail page
- Project list page
- Project detail page
- Opportunities page
- Opportunity detail page

## Informational Open House
On **Monday, December 12**, from 1**0:00-11:00 AM and 1:00-2:00 PM**, we will be hosting an informational drop-in session for interested developers to drop in and talk with our team about the work. If you’d like to attend, please email bcdevexchange@gov.bc.ca.

Please also feel free to ask questions via the comments section below.

## How to Contribute (How to Apply)

To apply for this work, please email a proposal to bcdevexchange@gov.bc.ca by **4:00 PM PDT on Wednesday, December 14, 2016**.  Please reference the issue name "Developing the BC Developers’ Exchange website front-end (BCDX-MTIC-004)" in your email.

## What to include in your proposal (evaluation criteria)
We will score your proposal by the following criteria:

1. Your confirmation of being able to commit the time to meet all of the Acceptance Criteria by January 13, 2016.
2. A short (around 200 words or less would be nice) summary of your experience working with agile projects (40 points).
3. References to your relevant experience and demonstrated ability to do the work (60 points). For example, a link to your GitHub projects.
4. With your proposal, you must attach a copy of the [Code-with-Us Terms](https://github.com/BCDevExchange/devex/blob/master/Code-with-Us%20Terms_BC%20Developers%20Exchange.pdf), with the required information asked for in the “Acceptance” section of the Terms inserted into the document (Mandatory).

If we are satisfied with the proposals, we will assign the work to the person with the highest scoring proposal by the end of the working day on Thursday, December 15, 2016. 

Here’s more detail about [how assignment works](https://github.com/BCDevExchange/code-with-us/wiki/4.-How-assignment-works)

## Questions, Comments, Suggestions?
Please post your questions in the comments section below.

**Comment by melavo** [comment]
Would I be able to attend the first meeting and then talk to you guys via skype or phone there after?  Thanks

**Comment by paulroberts68** [comment]
@melavo thanks for your enquiry. We haven't actually posted this opportunity yet but we're close to doing so. When we do I'll answer your question.

**Comment by paulroberts68** [comment]
@melavo regarding your question... this specific issue has been designed to test onsite collaboration between the assigned developer and the BC DevEx team. While we're testing this idea it doesn't mean that all CWU opportunities will need onsite collaboration. Having said that we do actually need the work done so we do encourage you to submit a proposal however preference will be given to proponents who are able to work side-by-side with our team for a couple of hours a day.

**Comment by mark-a-wilson** [comment]
Just a reminder of our information sessions today at 10:00 and 1:00 PM Pacific Time. If you would like to attend (virtually, or in person at 1012 Douglas Street in Victoria, BC), please send us an email: bcdevexchange@gov.bc.ca.  

We will post a summary of what's shared in the meetings here later today.

**Comment by mark-a-wilson** [comment]
We did host one information session yesterday at 1:00. Here is a video of that session:
https://youtu.be/q7DjmgpshNE

**Comment by mark-a-wilson** [comment]
Just another prompt/reminder to any who are watching this issue:  Proposals due by 4:00 PM Pacific today.

**Comment by mark-a-wilson** [comment]
Proposal period is now closed. Thanks to the two folks who submitted! We'll be evaluating later today and will let you know end of day today, or early tomorrow if we are making an assignment.

**Comment by mark-a-wilson** [comment]
We have scored the proposals and are assigning this work to @cywolf.

**Comment by daniel-johnson** [comment]
An interesting process, I like it.

**Comment by mark-a-wilson** [comment]
Thanks for the great work, @cywolf!
