### ISSUE TITLE
Odd behaviour after sign-in

### ISSUE THREAD

**Issue by DavidR8** [BCDevExchange/devex#90]
Account name is displayed twice
![screen shot 2017-02-09 at 8 45 20 am](https://cloud.githubusercontent.com/assets/4622563/22793289/4aefee7e-eea4-11e6-8995-21c5bb5fcb5b.png)

**Comment by ccoldwell** [comment]
cannot recreate, does it still say this when he logs in?

**Comment by DavidR8** [comment]
Yup it still does.
![screen shot 2017-02-09 at 11 19 24 am](https://cloud.githubusercontent.com/assets/4622563/22799181/b3fd2084-eeb9-11e6-9344-0357292b3c89.png)

**Comment by mark-a-wilson** [comment]
Haven't seen this again.  @DavidR8 are you still seeing it when you go to TEST? (What browser are you using?)

**Comment by DavidR8** [comment]
Yes I still am. I used Firefox
Cleared my cache.
Closed browser.
Restarted.
![screen shot 2017-02-09 at 6 26 15 pm](https://cloud.githubusercontent.com/assets/4622563/22811714/5f244ae2-eef5-11e6-8277-5134cc7587ed.png)

**Comment by DavidR8** [comment]
This is what happens in Safari. Looks like some kind of image 
![screen shot 2017-02-09 at 6 28 40 pm](https://cloud.githubusercontent.com/assets/4622563/22811764/ac30e016-eef5-11e6-937e-da45b4ea41f5.png)

When I click on the down-arrow I see this. Curious 'alignment' with the name.
![screen shot 2017-02-09 at 6 30 17 pm](https://cloud.githubusercontent.com/assets/4622563/22811800/e5625afe-eef5-11e6-9056-c2c1f1d116f2.png)

**Comment by DavidR8** [comment]
This looks like it's fixed so I'm closing the issue.
