### ISSUE TITLE
New Gov Users can't create program, project, opp

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevExchange/devex#91]
On TEST at 9:10 AM Feb 9
- David Wrate identified as a Gov User
- Mark logged in as admin and confirmed him as Gov User
- David refreshed and could then see '+ CREATE NEW' buttons
- Tried to create new opportunity; was given pop-up msg to create a project first
- Tried to create new project - was take to form with fields missing (e.g. no WYSIWYG, no program selector)

**Comment by ccoldwell** [comment]
fixed this with another warning and kick out to the user

**Comment by mark-a-wilson** [comment]
fixed!
