### ISSUE TITLE
Change incrementally to iteratively

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/devex#97]
Iterative is more commonly used by devs. 

On [http://platform-dev.pathfinder.gov.bc.ca/codewithus](http://platform-dev.pathfinder.gov.bc.ca/codewithus) under Developers

Change on this:

Work collaboratively and incrementally with the opportunity contact. 

to this:

Work collaboratively and iteratively with the opportunity contact.

**Comment by mark-a-wilson** [comment]
done
