### ISSUE TITLE
Add example that illustrates speed of Code-With-US

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/devex#98]
On [http://platform-dev.pathfinder.gov.bc.ca/codewithus](http://platform-dev.pathfinder.gov.bc.ca/codewithus) under Program Owners

Change on this:

Code With Us is a new way for the B.C. public sector to access talented developers and pay for code. Post an opportunity worth up to $10,000, evaluate proposals, choose a developer, and get to work!

to this:

Code With Us is a new way for the B.C. public sector to access talented developers and pay for code quickly. We completed a Code With Us in 15 business days from opportunity posted to code accepted. Post an opportunity worth up to $10,000, evaluate proposals, choose a developer, and get to work!

**Comment by mark-a-wilson** [comment]
excellent - thanks
