### ISSUE TITLE
What you need is a GitHub repo and to signup to the BCDevExchange

### ISSUE THREAD

**Issue by lmullane** [BCDevExchange/devex#99]
Changes are for consistent use of terms (i.e. opportunity vs technical contact)

And added GitHub

On [http://platform-dev.pathfinder.gov.bc.ca/codewithus](http://platform-dev.pathfinder.gov.bc.ca/codewithus) under Program Owners

Change on this:

What you need

To manage a Code With Us opportunity, you need:

Clearance to share your code under an open license. You may need to consult with your intellectual property program. Read the B.C. Government’s Guide for Open-Source Projects.

A technical contact - a person on your team who has the expertise and time to respond to questions and give direction to developers publicly on GitHub for the duration of the opportunity.

Get started

If you don't already have a GitHub account, create one.
Sign up on the BCDevExchange.
Create a profile for your program and project. This helps developers understand what you’re working on, and may entice more people to apply on the opportunity.

to this:

What you need to get started

If you don't already have a GitHub account, create one.

Sign up on the BCDevExchange.

Create a profile for your program and project. This helps developers understand what you’re working on, and may entice more people to apply on the opportunity.

Create a repo on GitHub, the popular online code sharing platform, to collaborate on your code. Talk to us about getting setup.

Clearance to share your code under an open license. You may need to consult with your intellectual property program. Read the B.C. Government’s Guide for Open-Source Projects.

An opportunity contact - a technical person on your team who has the expertise and time to respond to questions and give direction to developers publicly on GitHub for the duration of the opportunity.

**Comment by mark-a-wilson** [comment]
Thanks man
